### ISSUE TITLE
Bug in using (define-synthax …) without #:assert

### ISSUE THREAD

**Issue by lenary** [emina/rosette#10]
I wanted to do a simple `define-synthax`, something like the following:

```
(define-synthax (??const-or-var var-names ...)
  [choose
   (const (??))
   (var var-names) ...
  ])
```

Which should correspond to the following non-recursive grammar:
```
const-or-var ::= (const integer) | (var var-name)
var-name ::= var-names ...
```

However I get an error:
```
#%datum: identifier's binding is ambiguous
  at phase: 1
  in: #%datum
```

With the simple change of adding `#:assert #t`to the define-synthax, this error goes away and the grammar seems to create the right values. The docs say the assert is optional, and my understanding was that it was for making sure recursive grammars bottomed-out, so for a non-recursive grammar like mine, it shouldn't be needed.

Maybe I'm not understanding that with `…` the grammar becomes recursive anyway?

**Comment by jamesbornholt** [comment]
Looks like this broke with Racket 6.3's new macro expander. For the moment, use Racket 6.1 as the README suggests.
