### ISSUE TITLE
odd behavior with evaluating a box

### ISSUE THREAD

**Issue by alanborning** [emina/rosette#11]
If we evaluate a vector of one element, we get a new vector with the result of evaluating the contents. But it doesn't work with box.  Bug?

(define-symbolic x number?)
(define bx (box x))
(define v (vector x))
(solve (assert (= x 1)))
(evaluate bx)
(evaluate v)

**Comment by emina** [comment]
Yes, this is a bug in the master branch of Rosette.  It is fixed in the refactor-ops branch, which will become the master branch in a few weeks.

**Comment by emina** [comment]
P.S.  I have applied a patch to the master branch that should fix this problem.

**Comment by alanborning** [comment]
Thanks!  I'm now using the updated master branch and everything's working.
