### ISSUE TITLE
Old z3

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#110]
I had a very simple rosette query that gave rise to the attached smt (generated using `(output-smt)`) and yet Z3 could not solve it - or at least rosette's z3 which I just noticed is in version 4.4.2. I then installed z3 from my linux distro and got version 4.7.1 which solves the attached with no problems. Is it time to upgrade the z3 distributed with rosette?
[rosette15402957191540295719355.smt2.gz](https://github.com/emina/rosette/files/2506025/rosette15402957191540295719355.smt2.gz)

**Comment by jamesbornholt** [comment]
We've considered updating the Z3 version a few times -- we do test each new Z3 release, but each time we find (different) severe performance regressions on our benchmark suite. I just tested 4.8.1 (the newest release) and found several of our benchmarks were > 10x slower, and none got faster. So in the interests of stability, we probably won't update the distributed version for a while.

That said, Rosette 3.0 makes it easier to use a different solver version, by specifying the path to the binary:

```
(require rosette/solver/smt/z3)
(current-solver (z3 #:path "/full/path/to/z3"))
```

So if you find the newer Z3 releases work better for your queries, it should be easy to use those versions instead :-)

**Comment by pmatos** [comment]
Thanks @jamesbornholt . Have you reported the regressions upstream? It would be something upstream should be aware of.
