### ISSUE TITLE
contract violation when passing symbolic value as second argument of `expt` 

### ISSUE THREAD

**Issue by epeguero** [emina/rosette#116]
I ran into a problem with generating constraints using `expt`. 

This program works fine:

	#lang rosette/safe
	(define-symbolic y integer?)
	(expt y 2)

This one raises a contract violation:

	#lang rosette/safe
	(define-symbolic y integer?)
	(expt 2 y)

Maybe it’s intentional that `expt` can’t have a symbolic RHS, but in that case maybe the documentation should mention it. Probably on this page:
https://docs.racket-lang.org/rosette-guide/sec_bools_ints_reals.html

**Comment by emina** [comment]
This is intentional.  SMT solvers don't support `expt` so the first case, where the exponent is concrete, is expanded into a multiplication. There is no clean / faithful encoding for the second case (it's essentially a loop with an unknown upper bound).

**Comment by remysucre** [comment]
I ran into this as well, and agree documenting this would be helpful. Do other operations on numbers behave this way? I'm happy to help improving the doc.
