### ISSUE TITLE
[rosette-guide] debug example fails on render method

### ISSUE THREAD

**Issue by rachitnigam** [emina/rosette#121]
I was following the [Rosette Essentials](https://docs.racket-lang.org/rosette-guide/ch_essentials.html) guide. The following example doesn't work:

```racket
#lang rosette/safe
 
(require rosette/query/debug rosette/lib/render)
 
(define (poly x)
  (+ (* x x x x) (* 6 x x x) (* 11 x x) (* 6 x)))
 
(define/debug (factored x)       ; define/debug marks a procedure as part of
  (* x (+ x 1) (+ x 2) (+ x 2))) ; the code to be debugged
 
(define (same p f x)
  (assert (= (p x) (f x))))


(define ucore (debug [integer?] (same poly factored -6)))

(render ucore)
```
it fails with the message:
```
open-input-file: contract violation
  expected: path-string?
  given: 'unsaved-editor
```

The docs page says that this example should end up rendering the unsat core of the factored formula.

**Comment by emina** [comment]
These definitions needs to be saved to a file, as [specified in the guide](https://docs.racket-lang.org/rosette-guide/ch_essentials.html#%28part._sec~3adebug%29):

> First, save these definitions to a file
