### ISSUE TITLE
examining solver proofs?

### ISSUE THREAD

**Issue by stchang** [emina/rosette#122]
Does Rosette have any support for retrieving solver proofs?

A naive attempt results in an error that I can't figure out.

```racket
#lang rosette
(require rosette/solver/smt/z3)
(current-solver (z3 #:options (hash ':produce-proofs true)))
(define-symbolic n m integer?)
(verify (assert (implies (and (<= n m) (<= m n)) (= n m))))
```
=>
`read-solution: unrecognized solver output: (error line 2 column 29: invalid bit-vector literal, expecting 'x' or 'b')`

(I get the same error when I try to change any solver option though)

**Comment by sorawee** [comment]
Rosette seems to send `(set-option :produce-proofs #t)` to Z3 which is not syntactically valid.

**Comment by emina** [comment]
Yeah, right now, Rosette understands unsat cores but it doesn't have a notion of a solver proof. 

So, if the solver produces a proof, Rosette will fail / treat it as unknown output.

**Comment by stchang** [comment]
Ok thanks. Is there anything in the solver api (`smt-output`?) that will let me look at the raw solver output before rosette reads it?

Also I think something else is wrong (as @sorawee mentions) because I get the same error when I change `produce-proofs` in my above example to `produce-unsat-cores`.

Should the `#t` in the `set-option` be `true`?

**Comment by emina** [comment]
Yes, these options are sent directly to the solver as provided by the client.  (Rosette itself doesn't understand what the options mean.)

Here is the default procedure for reading the solver output:

https://github.com/emina/rosette/blob/master/rosette/solver/smt/base-solver.rkt#L133

You can also provide your own custom procedure: 

https://github.com/emina/rosette/blob/master/rosette/solver/smt/base-solver.rkt#L92

For example, `yices` uses its own reader:

https://github.com/emina/rosette/blob/master/rosette/solver/smt/yices.rkt#L113

**Comment by stchang** [comment]
In case someone looks at this thread in the future, I believe the `#:option` values must be symbols as well, eg with:

`(current-solver (z3 #:options (hash ':produce-unsat-cores 'true)))`

the `verify` query runs without error.

**Comment by emina** [comment]
Yes, indeed, they all need to be symbols.
