### ISSUE TITLE
Rosette returns unsat for satisfiable solve call

### ISSUE THREAD

**Issue by shoaibkamil** [emina/rosette#127]
We're not sure if this is just misuse/misunderstanding on our end, but consider the following:

```
(require rosette/lib/synthax)
(require rosette/lib/angelic rosette/lib/match)

(output-smt #t)

(define-symbolic ??dd integer?)
;; the following returns 2, as expected
(solve (assert (= (+ (/ 10 ??dd) (+ (/ 6 ??dd) (/ 4 ??dd))) 10)))
;; the following returns unsat
;(solve (assert (= (+ (/ 6 ??dd) (+ (/ 6 ??dd) (/ 4 ??dd))) 8)))
```
The first call correctly returns 2.

If we comment out the first `solve` call and uncomment the second, Rosette returns unsat.  However, if we run Z3 on the SMT2 file that Rosette outputs, Z3 correctly returns sat, and `(get-model)` correctly defines `c0` as 2.

**Comment by emina** [comment]
Hi Shaob,

This sounds like a solver / installation issue.

What version of Racket and Rosette are you using, and which solver?

With Racket 7.1, the latest version of Rosette (master branch), and the z3 solver provided with the Rosette installation, this code behaves as expected:

```
#lang rosette
 
(require rosette/lib/synthax)
(require rosette/lib/angelic rosette/lib/match)

(output-smt #t)

(define-symbolic ??dd integer?)
;; the following returns 2, as expected
(solve (assert (= (+ (/ 10 ??dd) (+ (/ 6 ??dd) (/ 4 ??dd))) 10)))
;; the following returns unsat
(solve (assert (= (+ (/ 6 ??dd) (+ (/ 6 ??dd) (/ 4 ??dd))) 8)))

;; this is what's printed at the REPL
Outputting SMT to file: /var/folders/gn/8xxvpnh947g0q1dgf1sn_rlw0000gp/T/rosette15681309871568130987738.smt2
(unknown)
(unsat)
```

**Comment by shoaibkamil** [comment]
Thanks for the quick response Emina!  You're right, this seems to be an issue with the underlying solver; apparently Z3 4.4.2 does not correctly handle this case.  Using Z3 4.8.5 behaves as expected.

```
#lang rosette
 
(require rosette/lib/synthax)
(require rosette/lib/angelic rosette/lib/match)
(require rosette/solver/smt/z3) 

(current-solver (z3 #:path "/usr/local/bin/z3"
                    #:options (solver-options (current-solver))))

(output-smt #t)

(define-symbolic ??dd integer?)
(solve (assert (= (+ (/ 6 ??dd) (+ (/ 6 ??dd) (/ 4 ??dd))) 8)))
```
REPL:
```
Outputting SMT to file: /var/folders/bp/rmkc3pv50dxdpx6s740g2pwr0000gn/T/rosette15681342411568134241267.smt2
(model
 [??dd 2])
```
