### ISSUE TITLE
[Feature Request] Dynamic generation of names for `define-symbolic*`

### ISSUE THREAD

**Issue by florence** [emina/rosette#128]
Context: I'm building a interpreter for a redex model in rosette. In the process it makes my life easier to generate symbolic inputs automatically based on the free variables of my program.

Unfortunately `define-symbolic*` decides the name for the variable statically, which makes the output of the models a little hard to read since there isn't a relationship between the names of the symbolic variables and the names of the original program.

The Request:
It would be nice to do something like:

```
(define (symbolic-boolean name)
    (make-symbolic* name boolean?))
```

where name is a symbol or string and the symbolic variable would display like
"<value-of-name>$<number>"

```
(define (symbolic-boolean)
    (define-symbolic b boolean?)
    b)
```

which always displays as "x$<number>".

**Comment by emina** [comment]
You can do this with Rosette's `constant` function:

```
#lang rosette

> (define x (constant "foo" boolean?))
> x
foo
```

This function creates a fresh symbolic constant with the given identifier (which can be any Racket value) and type.

But note that if you do this, you'll need to manage the names yourself---make sure they are unique.  If you create two symbolic constants with the same identifier, Rosette will treat them as the same constant:

```
> (define y (constant "foo" boolean?))
> (eq? x y)
#t 
```
