### ISSUE TITLE
Synhesize example from docs does not work when run in module.

### ISSUE THREAD

**Issue by LeifAndersen** [emina/rosette#13]
If I have the following module, based on the one in the docs:

```
#lang s-exp rosette/safe

(require rosette/query/debug
         rosette/lib/tools/render
         rosette/lib/meta/meta)

(define (poly x)
  (* (+ x 1) (+ x 1)))

(define (factor x)
  (+ (* x x) (* 2 x) (??))) ;; XXX: Should be 1

(define (same p f x)
  (assert (= (p x) (f x))))

(define-symbolic i number?)
(define binding
  (synthesize #:forall (list i)
              #:guarantee (same poly factor i)))
(print-forms binding)

```

I get the following output:
```
'(define (factor x) (+ (* x x) (* 2 x) 1))
```

However, if I move those last three lines into the repl, I get the following output:
```
'(define (factor x) (+ (* x x) (* 2 x) 1))
```

Is this expected behavior? (If so, can you please help me understand it?)

**Comment by emina** [comment]
Is there a typo in your message?  The two expressions are identical.

**Comment by LeifAndersen** [comment]
Whoops, it oddly enough seems to be working now. Earlier it was printing out:

```
'(define (same p f x) (assert (= (p x) (f x))))
```

(I copied that output after running it in the repl.)

So I'll see if I can figure out how to cause that to happen again.

Thank you.

**Comment by emina** [comment]
Generally speaking, print-forms will work reliably only when the synthesized forms appear in a saved module.  Basically, print-forms reads the module file in order to figure out how to map the solution obtained from the solver to code.  So, that may have been the problem.

**Comment by emina** [comment]
I would also like to add that Rosette 2.0 is coming out next month.  It has many cool new features and better performance.  But there are significant languages differences, so I hope you don't invest a lot of coding time into this version :)

**Comment by LeifAndersen** [comment]
Oh cool. Would it be possible to talk to you sometime about it? @bennn and I are planning on playing with Rosette as a part of our model checking class we're taking right now, and we would be interested in putting our work to good use. :)

**Comment by bennn** [comment]
@LeifAndersen I'm happy to just wait for Rosette 2.0

**Comment by emina** [comment]
Sure, I'd be happy to chat!  If you send an email to my cs.washington.edu account, we can take the scheduling offline.
