### ISSUE TITLE
Problems in Rosette's quasiquote and unquote-slicing's handling of symbolic list

### ISSUE THREAD

**Issue by zyh3838438zyh** [emina/rosette#131]
The program below seems not to work as expected:

```racket
#lang rosette

(define-symbolic e0 e1 e2 integer?)
(define lst (list e0 e1 e2))
(define a (filter (curry > 1) lst))
(define b `(1 ,@a))
(displayln (list? a)) ;; #t, as expected
(displayln (list? b)) ;; #f, should be #t
```

It seems that `b` is treated here as a `cons` of concrete `1` and the symbolic list `a`, while it's expected to be merged as a single symbolic value (as `(cons 1 a)`).

**Comment by zyh3838438zyh** [comment]
On second thought I found this may simply be an unlifted operation in racket, so rosette does not have special handling of this kind of operations. Since rosette and racket programs often use quote/unquote mechanics for simplicity, is it reasonable to add support for quasi quote/unquote-slicing in rosette?

**Comment by emina** [comment]
Right, quote/unquote/quasiquote are not lifted.  They have [complex semantics](https://docs.racket-lang.org/reference/quasiquote.html) that would be difficult (and fragile) to lift.
