### ISSUE TITLE
no type checking in `verify`?

### ISSUE THREAD

**Issue by gshen42** [emina/rosette#133]
There is no type error when running this code:
```
#lang rosette

(verify (vector-ref 3 4))
```
Is this the intended behaviour?

**Comment by emina** [comment]
Yes, Rosette treats all errors are treated as assertions failures.  Note that the `verify` query produces an empty model, indicating that this code fails unconditionally on all paths.  To make this easier to see, you can refactor your code as follows:

```
#lang rosette

(define (bad) (vector-ref 3 4))

> (verify (bad))
(model)

> (bad)
vector-ref: contract violation
  expected: #<procedure:vector?>
  given: 3
```
