### ISSUE TITLE
Building Rosette 3.0 under Racket CS 7.5 crashes on Windows

### ISSUE THREAD

**Issue by dnm** [emina/rosette#139]
Hello,

Attempting to build Rosette 3.0 from source via `raco pkg install` using Racket CS 7.5 (64-bit) on Windows 10 crashes during the process, and displays a standard Windows 10 crash message/dialog ("Racket application has stopped working").

Following the same build & installation procedure for Racket 7.5 works fine and does not have this problem.

(FWIW, I originally experienced this issue under Racket CS 7.4, but I've since upgraded to 7.5 for both Racket and Racket CS [I run and use both, not just the latter], and I didn't capture enough information when I ran into this for CS 7.4. However, I just tried under CS 7.5 and got similar [if not identical] results, so I figured I'd just quickly write this up and log the bug. Also, similar to what was seen above for regular [non-CS] Racket 7.5, Racket 7.4 had no issues with this build & install either).

All Racket versions mentioned above are 64-bit.
OS: Windows 10 64-bit (OS Version: 10.0.16299 N/A Build 16299)

Command prompt output from `raco pkg install` attempt follows; this is what gets printed before the crash dialog appears. Seems to be dying in `<pkgs>/rosette/rosette/solver/smt` from the looks of things.

```text
C:\Users\Fnord\Hack\rosette-3.0\rosette>raco pkg install
Linking current directory as a package
raco setup: version: 7.5
raco setup: platform: win32\x86_64 [cs]
raco setup: target machine: ta6nt
raco setup: cross-installation: yes
raco setup: installation name: 7.5
raco setup: variants: cs
raco setup: main collects: C:\Dev\RacketCS7.5\collects\
raco setup: collects paths:
raco setup:   C:\Users\Fnord\AppData\Roaming\Racket\7.5\collects
raco setup:   C:\Dev\RacketCS7.5\collects\
raco setup: main pkgs: C:\Dev\RacketCS7.5\share\pkgs
raco setup: pkgs paths:
raco setup:   C:\Dev\RacketCS7.5\share\pkgs
raco setup:   C:\Users\Fnord\AppData\Roaming\Racket\7.5\pkgs
raco setup: links files:
raco setup:   C:\Dev\RacketCS7.5\share\links.rktd
raco setup:   C:\Users\Fnord\AppData\Roaming\Racket\7.5\links.rktd
raco setup: main docs: C:\Dev\RacketCS7.5\doc
raco setup: --- updating info-domain tables ---                    [16:12:18]
raco setup: updating: C:\Users\Fnord\AppData\Roaming\Racket\7.5\share\info-cache.rktd
raco setup: --- pre-installing collections ---                     [16:12:18]
raco setup: pre-installing: <pkgs>/rosette/rosette
raco setup: --- installing foreign libraries ---                   [16:12:18]
raco setup: --- installing shared files ---                        [16:12:18]
raco setup: --- compiling collections ---                          [16:12:18]
raco setup: --- parallel build using 4 jobs ---                    [16:12:18]
raco setup: 3 making: <pkgs>/rosette/bin
raco setup: 3 making: <pkgs>/rosette/rosette
raco setup: 2 making: <pkgs>/rosette/sdsl
raco setup: 2 making: <pkgs>/rosette/test
raco setup: 3 making: <pkgs>/rosette/rosette/base
raco setup: 3 making: <pkgs>/rosette/rosette/base/adt
raco setup: 3 making: <pkgs>/rosette/rosette/base/core
raco setup: 3 making: <pkgs>/rosette/rosette/base/form
raco setup: 3 making: <pkgs>/rosette/rosette/base/struct
raco setup: 3 making: <pkgs>/rosette/rosette/base/util
raco setup: 3 making: <pkgs>/rosette/rosette/lang
raco setup: 3 making: <pkgs>/rosette/rosette/lib
raco setup: 3 making: <pkgs>/rosette/rosette/lib/profile
raco setup: 3 making: <pkgs>/rosette/rosette/lib/profile/renderer
raco setup: 3 making: <pkgs>/rosette/rosette/lib/profile/renderer/report
raco setup: 3 making: <pkgs>/rosette/rosette/lib/profile/renderer/report/html
raco setup: 3 making: <pkgs>/rosette/rosette/lib/profile/renderer/report/html/css
raco setup: 3 making: <pkgs>/rosette/rosette/lib/profile/renderer/report/html/js
raco setup: 3 making: <pkgs>/rosette/rosette/lib/synthax
raco setup: 3 making: <pkgs>/rosette/rosette/lib/util
raco setup: 3 making: <pkgs>/rosette/rosette/private
raco setup: 3 making: <pkgs>/rosette/rosette/query
raco setup: 3 making: <pkgs>/rosette/rosette/safe
raco setup: 3 making: <pkgs>/rosette/rosette/safe/lang
raco setup: 3 making: <pkgs>/rosette/rosette/solver
raco setup: 3 making: <pkgs>/rosette/rosette/solver/mip
raco setup: 3 making: <pkgs>/rosette/rosette/solver/smt
```

**Comment by emina** [comment]
Hi, and thanks for the report!  Given that this is happening with a specific version of Racket on Windows, my best guess is that it is due to a Racket issue.  No one on our team uses Windows so, unfortunately, our ability to diagnose this further is limited.  It might still be worth reporting to the Racket team though.

**Comment by dnm** [comment]
Hi Emina,

Yeah, I agree with you. I think this is a Racket CS issue (though to be fair, I have no data to prove that -- I haven't done the necessary digging -- but still, that's my intuition) rather than a Rosette-specific issue. And I know Windows isn't "officially" supported, so I'm not expecting anything (not that I think any expectations would be warranted on Linux or Mac either, to be fair). I just wanted to log the issue for posterity's sake more than anything else, especially if anyone else happens to encounter this or something like it. Out of curiosity, have you or has anyone else tried building Rosette 3.0 (or later) under Racket CS on any other platform?

If I find (read: make) time, I may investigate futher and take up your suggestion of reporting this to Racket devs, but my track record on that would caution against expectations there as well. ;)

**Comment by emina** [comment]
Yes, that's fair :)

I believe that @jamesbornholt has successfully built Rosette 3.x under Racket CS on Mac or Linux.

**Comment by jamesbornholt** [comment]
Yep, there were issues with Rosette + Racket CS in 7.4, but they were [fixed in Racket](https://github.com/racket/racket/pull/2745) for 7.5.
