### ISSUE TITLE
Verify returns incorrect counter example for integers bigger than 15

### ISSUE THREAD

**Issue by LeifAndersen** [emina/rosette#14]
Perhaps this is not worth fixing with Rosette 2 coming out, but it still seems like interesting (or at least unexpected) behavior to me.

Consider the following program that compares an identity function with an almost identity function that gives the wrong value if it is applied with `16`:

```
#lang s-exp rosette/safe

(define (almost-identity x)
  (if (= x 16)
      17
      x))

(define (identity x)
  x)

(define (same id1 id2 x)
  (assert (= (id1 x) (id2 x))))

(define-symbolic i number?)
(define cex (verify (same identity almost-identity i)))
```

Rosette correctly determines that these are not the same function (and if I 'fix' `almost-identity` to be an actual identity function it also correctly fails to find a counter example).

However, the counter example it produces does not seem correct:

```
> cex
(model
 [i -16])
```

If we change `almost-identity` to break on 17, the i in the counter example changes to -15, 18 turns to -14 and so on up until 32 turns into 0. After that it seems to wrap between 0 and 32, depending on the value passed into it.

I'm wondering if this is related to the Java portion of the solver, where counter examples are only given a nibble of memory.

For what it's worth though, it does seem to correctly identify when something is wrong, just not why.

**Comment by emina** [comment]
In Rosette 1.0, all symbolic numeric operations are reduced to finite precision arithmetic, regardless of which underlying solver is used.  The precision of this reduction is controlled by the `current-bitwidth` parameter.  By default, that parameter is set to 5.  This is why you are observing this behavior.

Rosette 2.0 allows you to use infinite-precision arithmetic.  Of course, there are decidability issues involved with this, but 2.0 lets you decide which SMT theory (bitvectors, integers, or reals) to use for numeric operations.
