### ISSUE TITLE
Time taken to synthesize

### ISSUE THREAD

**Issue by ojas1** [emina/rosette#143]
I'm trying to run the synthesis example given in the [guide](https://docs.racket-lang.org/rosette-guide/ch_essentials.html). 

I executed the following function
`(define binding
    (synthesize #:forall (list x)
                #:guarantee (same poly fact x)))`

and i've been waiting for it to complete for almost five minutes now.

Am I doing something wrong?  How long should it take?

**Comment by jamesbornholt** [comment]
It should be much faster than that! I ran this program, which I copied and pasted from the docs (and added the call to `time`):

```racket
#lang rosette

(require rosette/lib/synthax)
 
(define (poly x)
 (+ (* x x x x) (* 6 x x x) (* 11 x x) (* 6 x)))
 
(define (factored x)
 (* (+ x (??)) (+ x 1) (+ x (??)) (+ x (??))))
 
(define (same p f x)
 (assert (= (p x) (f x))))

(define-symbolic i integer?)
(define binding
  (time (synthesize #:forall (list i)
                    #:guarantee (same poly factored i))))
```

and it completes in < 1 second. Could you try running this program?

If it's still slow, one way to investigate further is using Rosette's profiler -- running `raco symprofile --stream file.rkt` will open your browser and show you what calls the program is making (and so hopefully where it is hung up).

**Comment by ojas1** [comment]
It is working.  I had actually modified the definition of `fact` to the following:

`(define (fact x)
  (* x (+ x (??)) (+ x (??)) (+ x (??))))`

Zero is also a factor, so it should work, but this does not work.  What may be the reason?

**Comment by sorawee** [comment]
This query involves non-linear integer arithmetic, which in general is undecidable. So you should not expect that this kind of query will _always_ work. To guarantee that you will get an answer, when you use Rosette in practice, you should make sure that you are using decidable theories, like linear integer arithmetic or bitvector.

For your specific example, Rosette has [`current-bitwidth`](https://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_rosette.html#%28def._%28%28lib._rosette%2Fquery%2Ffinitize..rkt%29._current-bitwidth%29%29) which can be used to turn integer operations into bitvector operations. With this, we are now using the theory of bitvector which is decidable, so you can expect that it will _return_ (with or without an answer):

```
#lang rosette

(current-bitwidth 16) ;; use 16 bits bitvector

(require rosette/lib/synthax)
 
(define (poly x)
 (+ (* x x x x) (* 6 x x x) (* 11 x x) (* 6 x)))

(define (factored x) (* x (+ x (??)) (+ x (??)) (+ x (??))))
 
(define (same p f x)
 (assert (= (p x) (f x))))

(define-symbolic i integer?)
(define binding
  (time (synthesize #:forall (list i)
                    #:guarantee (same poly factored i))))

binding

#| 
cpu time: 219 real time: 470 gc time: 0
(model
 [??:untitled:11:32 1]
 [??:untitled:11:43 2]
 [??:untitled:11:54 3])
|#
```

In this particular case, there is an answer. Note though that using bitvector semantics means that you need to deal with integer overflow. Therefore, the answer might be unexpected, and you should be careful.

**Comment by ojas1** [comment]
Thanks for the help and explanation.  I wonder if this question was more suitable for StackOverflow.
