### ISSUE TITLE
"doc" source directory conflicts with package meaning

### ISSUE THREAD

**Issue by mflatt** [emina/rosette#144]
The package manager considers a "doc" directory to be generated, along the same lines as "compiled". That was probably a bad choice in the design of the package-system, but the effect is that installing the "rosette" package in source mode strips away the "doc" directory content (as described at https://docs.racket-lang.org/pkg/strip.html), which means that the package installation fails.

Source-mode installs are currently rare, so the "doc" directory here probably isn't causing anyone else trouble, but I happened to run into this today.

Renaming the "doc" directory to anything other than "doc" or "compiled" — and changing the reference at https://github.com/emina/rosette/blob/master/rosette/info.rkt#L8 — would let the "rosette" package install cleanly in source mode.

**Comment by emina** [comment]
Thanks, Matthew!

I always wondered why all those files got generated into the `doc` directory ... mystery solved. 

I pushed a fix (that hopefully doesn't break other things).
