### ISSUE TITLE
optional argument in member

### ISSUE THREAD

**Issue by stechu** [emina/rosette#151]
Racket `member` supports an optional argument, which is a customizable comparing function:
`(member v lst [is-equal?])`, Rosette doesn't support this optional argument yet.

Not sure is there any inherent difficulty of supporting `[is-equal?]`, but definitely it would be help to if support could be added. 
(I should be able to get around this though, just the code would not look as clean)

**Comment by emina** [comment]
There is no inherent difficulty in supporting this optional argument.  It's possible to achieve the desired effect with `memf` though, with roughly the same amount of code.  For example:

```
#lang rosette

(define-symbolic xs integer? [5])

(define (abs= x y) (= (abs x) (abs y)))

(memf (curry abs= 3) xs)
```

This has the same effect as `(member 3 xs abs=)` would.

**Comment by stechu** [comment]
Thank you!
