### ISSUE TITLE
Folds on bitvectors?

### ISSUE THREAD

**Issue by whitequark** [emina/rosette#152]
While working on generating run-length limited line codes with Rosette I found that using folds on bitvectors is kind of awkward. Would it be useful to have something like `bvfold` in the Rosette standard library for "sideways" operations on bit vectors, like population count, find-first/last-1, run length, etc?

**Comment by emina** [comment]
Yes, that sounds useful.  Do you have an example of the kind of code you had to write?

**Comment by whitequark** [comment]
Sure. Popcnt, ff1 and fl1 should be obvious; right now I'm working on multiple run length related assertions, e.g. this one:
```
(define (assert-run-length bv #:min [min-run-length #f] #:max [max-run-length #f])
 (define bv-size (bitvector-size (type-of bv)))
 (define (collect-runs index run-started run-length)
  (if (eq? index bv-size)
      (assert run-started)
      (if (eq? (bitvector->natural (extract index index bv)) 1)
       (begin
        (if (not run-started) (void)
         (begin
          (if (eq? min-run-length #f) (void) (assert (>= run-length min-run-length)))
          (if (eq? max-run-length #f) (void) (assert (<= run-length max-run-length)))))
        (collect-runs (add1 index) #t 0))
       (collect-runs (add1 index) run-started (add1 run-length)))))
 (collect-runs 0 #f 0))
```
Most importantly, using a fold would mean it no longer has to use `bitvector-size`.

**Comment by whitequark** [comment]
(Aside: Rosette so far produces very nice results when generating RLL line codes, and based on preliminary results, I think it actually made not only possible but almost trivially easy two of my small research projects!)

**Comment by emina** [comment]
Got it.  And for a bitvector fold, you'd like to write something like `(bvfoldl p init bv)` ? 

I will leave this issue open and come back to it, hopefully soon-ish. 

(And cool result!  Really happy to hear that :)

**Comment by whitequark** [comment]
> And for a bitvector fold, you'd like to write something like `(bvfoldl p init bv)` ?

Yup, just like a fold on lists, probably returning a `#t` or `#f` at a time. (Though I think right now the bitvector type never explicitly assigns its bits any particular type?)

**Comment by emina** [comment]
Yes, bitvectors are treated as a primitive datatype, as in SMT, rather than, say, a sequence of T/F values, so we don't assign any type to the individual bits.

**Comment by whitequark** [comment]
Sounds great! I'm not sure how hard it is to make `bvfoldl` take multiple bit vectors. It seems handy in some cases, but the only one that came up so far (below) would still require the use of `bitvector-size` if `bvfoldl` would match the semantics of normal `foldl` with regards to length of multiple collections.

```racket
(define (assert-prefix-codebook codebook)
 ; asserts that no two encodings have the same prefix in given codebook
 (for-each-distinct-encoding-pair
  (lambda (first-encoding second-encoding)
   (define first-output  (encoding-output first-encoding))
   (define second-output (encoding-output second-encoding))
   (define prefix-size (min (bitvector-size (type-of first-output))
                            (bitvector-size (type-of second-output))))
   (assert (not (bveq (extract (- prefix-size 1) 0 first-output)
                      (extract (- prefix-size 1) 0 second-output)))))
  codebook))
```

**Comment by emina** [comment]
Yes, `bvfoldl` should be able to take as input an arbitrary bitvector, including a symbolic union of bitvectors.  That is, it should work on a value like this one `(if b (bv 1 4) (bv 2 16))` where `b` is a symbolic value so the result in a symbolic union of two bitvectors of different lengths.

**Comment by whitequark** [comment]
Sorry, I wasn't clear. I meant that `foldl` can take multiple lists like in `(foldl (lamba (a b acc) (displayln a b)) #f (list 1 2 3) (list 4 5 6))`.

**Comment by emina** [comment]
Ah, I see.  Yes, that's doable too.

**Comment by whitequark** [comment]
Thank you! This is awesome, and will help me a lot going forward :)

**Comment by emina** [comment]
Glad to hear it! :)

**Comment by emina** [comment]
And here is a small demo for `popcount` using the new library:

```
#lang rosette

(define (popcount x)
  (count (lambda (b) (not (bvzero? b))) (bitvector->bits x)))

> (popcount (bv #b1010 4))
2

> (define-symbolic x (bitvector 4))
> (popcount x)
(+ (ite (bveq (bv #b0 1) (extract 0 0 x)) 0 1) (ite (bveq (bv #b0 1) (extract 1 1 x)) 0 1) (ite (bveq (bv #b0 1) (extract 2 2 x)) 0 1) (ite (bveq (bv #b0 1) (extract 3 3 x)) 0 1))
```

**Comment by whitequark** [comment]
Oh, that's very elegant!
