### ISSUE TITLE
Compilation time of (and ...) form is quadratic in the number of forms

### ISSUE THREAD

**Issue by anishathalye** [emina/rosette#155]
To reproduce this, you can create a file like the following:

```racket
#lang rosette/safe
(and #t #t ... #t)
```

The time to `raco make` this file appears to be quadratic in the number of `#t`s in the body of the `and`.

![plot](https://user-images.githubusercontent.com/3526486/81179036-1ab26300-8f77-11ea-87ee-ba02f327a603.png)

(the workaround line is for the workaround below)

I don't have a deep understanding of Rosette/Racket internals. Briefly looking at the definitions in `control.rkt` and looking at the expansion of the `(and #t #t ... #t)` in the macro stepper, I wasn't able to figure out for sure why it was slow.

Here is the relevant code defining `and`:

```racket
(define-syntax (@and stx)
  (syntax-case stx ()
    [(_) (syntax/loc stx #t)]
    [(_ arg) (syntax/loc stx arg)]
    [(_ arg0 arg ...) (syntax/loc stx (@if arg0 (@and arg ...) #f))]))
```

Could it be that `syntax-case`'s runtime is linear in the size of the form, and so the total time taken is n+(n-1)+...+1, resulting in O(n^2) behavior? The workaround I used (given below) creates a binary tree of forms with logarithmic depth, so I think the runtime would be n + 2*(n/2) + 4*(n/4) + ..., with a logarithmic number of terms in the sum, resulting in O(n log n) behavior?

The simple benchmarking script that I used:

```python
import subprocess
import time

def main():
    for lang in ['racket', 'rosette/safe']:
        output_filename = '{}.txt'.format(lang.replace('/', '_'))
        with open(output_filename, 'w') as log:
            for mem in range(0, 2050, 50):
                with open('test.rkt', 'w') as f:
                    f.write('#lang {}\n'.format(lang))
                    terms = ['#t' for i in range(mem)]
                    f.write('(and {})\n'.format(' '.join(terms)))
                start = time.time()
                subprocess.check_call(['raco', 'make', 'test.rkt'])
                end = time.time()
                log.write('{} {}\n'.format(mem, end-start))

if __name__ == '__main__':
    main()
```

For now, I'm using the following workaround to emit a tree of Rosette `and` forms, which seems to greatly speed up compile time (included in the plot above). Sharing in case anyone else would find this useful:

```racket
(define-syntax (tree-and stx)
  (syntax-parse stx
    [(_) #'#t]
    [(_ arg) #'arg]
    [(_ arg0 arg1) #'(and arg0 arg1)]
    [(_ arg ...)
     (let* ([elems (syntax->list #'(arg ...))]
            [mid (quotient (length elems) 2)])
       (let-values ([(left right) (split-at elems mid)])
         #`(and
            (tree-and #,@left)
            (tree-and #,@right))))]))
```

**Comment by emina** [comment]
Thank you for the report!

We're looking into it.

@sorawee discovered at least one source of inefficiency that we weren't aware of, explained here https://github.com/racket/racket/issues/3162

Though this doesn't fully account for the slowdown you're seeing, so we'll continue investigating.
