### ISSUE TITLE
(Question:) What would it take to implement eager concretization?

### ISSUE THREAD

**Issue by Kingloko** [emina/rosette#161]
From the docs in section 9.1.4: 

> ... but the conditional establishes that the only possible values for that index are 0 or 1. When the Rosette SVM evaluates the first side of the conditional, it does not simplify the value of idx to be only 0 or 1, and so the resulting encoding creates infeasible branches ...

a) Would you be open to a PR that would include a concretization strategy that would avoid this problem? 
b) If (a) what level of effort and what kind of modifications do you expect it would take to implement this feature?

**Comment by emina** [comment]
Eager concretization is not a good idea in general.  It helps some examples but not others.  If not done judiciously, it can cause Rosette symbolic evaluation to degrade to symbolic execution, which is worst-case exponential. 

For that reason, eager concretization is not implemented in Rosette's core.

The best way to navigate the tradeoff between too much and not enough concretization is to implement application-specific symbolic optimizations, guided by symbolic profiling. 

A good example of how to do this is the [Serval](https://unsat.cs.washington.edu/projects/serval/) system, described in this paper: https://unsat.cs.washington.edu/papers/nelson-serval.pdf
