### ISSUE TITLE
Asserted expression evaluates to true under solution from `verify`

### ISSUE THREAD

**Issue by remysucre** [emina/rosette#170]
The call to `verify` in the end of this [program](https://github.com/remysucre/pier/blob/symbolic/pier.rkt) (L217) returns a solution, indicating the assertion is invalid. However the asserted expression evaluates to `#t` under the solution (L220). Does this indicate a bug, or am I misunderstanding how `verify` works? Thanks in advance.

**Comment by remysucre** [comment]
I shall add that, after uncommenting L211, 212 & 215, `verify` returns `(unsat)` on L215. However I expect L215 to be equivalent to L217.

**Comment by remysucre** [comment]
Re-reading the doc for `verify`, I see there is a difference between assertions evaluated before invoking `verify` and those evaluated during `verify`. So `verify` may still return a solution even if the explicit assertion in the argument is true.

**Comment by sorawee** [comment]
I would not trust the `unsat` result. Here's a similar program that exhibits the same behavior:

```
#lang rosette/safe

(define-symbolic b boolean?)

(define (f)
  (assert (forall (list b) b))
  2)

(verify (assert (= 1 (f))))
;; (model)

(define val (f))
(verify (assert (= 1 val)))
;; (unsat)
```

You might expect the second `verify` to result in `(model)`, but it's `(unsat)` because the call `(f)` generates a (false) assertion, which becomes an assumption in the `verify` query, so the verification succeeds trivially.

**Comment by sorawee** [comment]
Ah, just saw that you discovered that already :)

**Comment by sorawee** [comment]
FYI: another thing to look out for is the use of `define-symbolic*`, since it generates different symbols every time it's run. 

```
(define sol (verify (assert (f)))) ;; sol contains `var$0`
(evaluate (f) sol) ;; evaluate against `var$1`
```
