### ISSUE TITLE
Unable to optimize an expression that works with synthesize

### ISSUE THREAD

**Issue by resistor** [emina/rosette#180]
I'm trying to use Rosette to solve for a magic constant for a particular application. I've successfully written the assertions, and can ruse `synthesize` to generate a constant that satisfies the assertions. However, that constant is not unique, so I would like to use `optimize` to find the smallest constant that satisfies the assertions. Unfortunately, `optimize` does not support a `#:forall` parameter like `synthesize` does. I've attempted to work around this manually, using `forall` expressions in the `#:guarantee` parameter to `optimize`, without success. Is there a better way to do this?

Sample program attached below

```
#lang rosette/safe

; x - The input 
; c1 - The magic constant we will solve for
(define-symbolic x c1 (bitvector 16))

; Assert that all bit positions in the input other than the low four bits will be zero
(assert (bvult x (bv 16 16)))

; Synthesize a value of c1 that satisfies the above constraints, plus the requirement to map
; the input bits to their correct positions in the output.
; NOTE: This works and solves for a valid value of c1
(synthesize
  #:forall (list x)
  #:guarantee
  (assert
    (let ([mul (bvmul c1 x)])
      (and
        (bveq (bit 15 mul) (bit 3 x))
        (bveq (bit 14 mul) (bit 2 x))
        (bveq (bit  8 mul) (bit 1 x))
        (bvzero? (bit 6 mul))
        (bvzero? (bit 5 mul))
        (bvzero? (bit 4 mul))
        (bveq (bit  0 mul) (bit 0 x))
      )
    )
  )
)

; Solve for the smallest value of c1 that satisfies the assertions.
; NOTE: This seems to always return unsat
(optimize
 #:minimize (list (bitvector->integer c1))
 #:guarantee
 (forall (list x)
   (assert
    (let ([mul (bvmul c1 x)])
      (and
        (bveq (bit 15 mul) (bit 3 x))
        (bveq (bit 14 mul) (bit 2 x))
        (bveq (bit  8 mul) (bit 1 x))
        (bveq (bit  0 mul) (bit 0 x))
      )
    )
   )
  )
 )
```

**Comment by emina** [comment]
The `optimize` query is basically the same as the `solve` query, with the addition of the objective.  Converting `synthesize` to `solve` with a universal quantifier is tricky.  There are two problems here.

First, quantifiers behave intuitively only when the body is a pure expression; here, `assert` is a side effect.  Second, the assumption `(assert (bvult x (bv 16 16)))` is issued outside of the scope of the quantifier, so the `x` in `(bvult x (bv 16 16))` is a free variable in the resulting encoding (i.e., it's not bound by `forall`).  For the `optimize` query to have the same meaning as the `synthesize` query, this variable `x` must be in the quantified scope.

With all of this in mind, we can write this `optimize` query as follows.  I'm pretty surprised that the solver returns any result here, since it's not entirely clear what guarantees are provided for optimization in the presence of quantified formulas.  But that's a question for Z3 devs :) 

```
#lang rosette/safe

; x - The input 
; c1 - The magic constant we will solve for
(define-symbolic x c1 (bitvector 16))

; Assert that all bit positions in the input other than the low four bits will be zero
(assert (bvult x (bv 16 16)))

; Synthesize a value of c1 that satisfies the above constraints, plus the requirement to map
; the input bits to their correct positions in the output.
; NOTE: This works and solves for a valid value of c1
(synthesize
  #:forall (list x)
  #:guarantee
  (assert
    (let ([mul (bvmul c1 x)])
      (and
        (bveq (bit 15 mul) (bit 3 x))
        (bveq (bit 14 mul) (bit 2 x))
        (bveq (bit  8 mul) (bit 1 x))
        (bvzero? (bit 6 mul))
        (bvzero? (bit 5 mul))
        (bvzero? (bit 4 mul))
        (bveq (bit  0 mul) (bit 0 x))
      )
    )
  )
)

(asserts)
(clear-asserts!) ; Get rid of the out-of-scope assert.
(asserts)

(optimize 
 #:minimize (list c1)
 #:guarantee
 (assert
  (forall (list x)
          (=> (bvult x (bv 16 16)) ; Pull the assumption into the formula.
              (let ([mul (bvmul c1 x)])
                (and
                 (bveq (bit 15 mul) (bit 3 x))
                 (bveq (bit 14 mul) (bit 2 x))
                 (bveq (bit  8 mul) (bit 1 x))
                 (bveq (bit  0 mul) (bit 0 x))
                 )
                )
              )
          )
  ))
```

**Comment by resistor** [comment]
Thank you!

**Comment by emina** [comment]
P.S., one way to solve optimal synthesis problem is through repeated invocation of `synthesize`, with increasingly tighter bounds:

```
#lang rosette/safe

; x - The input 
; c1 - The magic constant we will solve for
(define-symbolic x c1 (bitvector 16))

(define (synth-bound b)
  (synthesize
   #:forall (list x)
   #:assume
   (assert (bvult x (bv 16 16)))
   #:guarantee
   (begin
     (assert b)
     (assert
      (let ([mul (bvmul c1 x)])
        (and
         (bveq (bit 15 mul) (bit 3 x))
         (bveq (bit 14 mul) (bit 2 x))
         (bveq (bit  8 mul) (bit 1 x))
         (bvzero? (bit 6 mul))
         (bvzero? (bit 5 mul))
         (bvzero? (bit 4 mul))
         (bveq (bit  0 mul) (bit 0 x))
         ))) )))


(let loop ([cur (synth-bound #t)] [prev (unsat)])
  (cond
    [(unsat? cur) prev]
    [else
     (printf "Best so far: ~a\n" (cur c1))
     (loop (synth-bound (bvult c1 (cur c1))) cur)]))
```

**Comment by resistor** [comment]
I had actually done something like that already, by manually adding assertions to constrain bits of `c1` to be zero until I found the smallest constant.

**Comment by emina** [comment]
Yes, your intuition was right.  This sort of loop is usually how most tools solve optimal synthesis problems.  (And, of course, the implementation of the loop gets much more complicated depending on what you have to do.)
