### ISSUE TITLE
`optimize` raises an error about `for`

### ISSUE THREAD

**Issue by rfindler** [emina/rosette#186]
Running this program:

```
#lang rosette/safe
(define-symbolic* class-var integer?)
(optimize
 #:minimize (if (= class-var 0) 1 0)
 #:guarantee #true)
```

produces this error

```
Welcome to DrRacket, version 8.0.0.13--2021-04-02(601f4a76/d) [cs].
Language: rosette/safe, with debugging; memory limit: 128 MB.
. . for: expected a sequence for t, got something else: (ite (= 0 class-var$0) 1 0)
> 
```

with a stacktrace pointing [here](https://github.com/emina/rosette/blob/master/rosette/solver/smt/z3.rkt#L98).

**Comment by sorawee** [comment]
According to [the documentation](https://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_rosette.html?q=minimize#%28part._.Optimization%29), `min-expr` should satisfy the contract `(listof (or/c integer? real? bv?))
`. Wrapping the `if` expression with `list` seems to solve the problem.

```
#lang rosette/safe
(define-symbolic* class-var integer?)
(optimize
 #:minimize (list (if (= class-var 0) 1 0))
 #:guarantee #true)
```
