### ISSUE TITLE
Unsound simplification of (/ x x) to 1

### ISSUE THREAD

**Issue by remysucre** [emina/rosette#187]
It seems rosette simplifies `(/ x x)` to 1 where x is symbolic ([this line](https://github.com/emina/rosette/blob/ac96664ae9f4060b40085f849e74793d17abbd3d/rosette/base/core/real.rkt#L477)). This is unsound since `x` can be 0, as illustrated by the following program: 

```
#lang rosette
(define-symbolic a real?)
(verify (assert (eq? (/ a a) 1)))
(/ a a)
(verify (assert (eq? (/ a a) 1)))
```
Running it results in SAT, 1, and then UNSAT, which is rather confusing. Can we just remove that simplification rule?

**Comment by remysucre** [comment]
The first rule simplifying `(/ 0 x)` to 0 is unsound too.

**Comment by emina** [comment]
Rosette treats division by zero as an error by emitting an assertion to ensure that the divisor, in this case `a`, cannot be zero.  

This is why you get the counterexample for the first `verify` query.  To see why you don't get one for the second, note that running `(/ a a)` at the top level emits the assertion `(! (= a 0))`, which is treated as an assumption to the second `verify` expression, as explained in the doc. 

The simplifications are fine in the sense that they don't affect soundness, thanks to the emitted assertion.  You will always get a counterexample when the divisor can be zero.

This interaction that shows the top-level assertion being emitted:

```
#lang rosette

(define-symbolic a real?)

(verify (assert (eq? (/ a a) 1)))

(vc)

(/ a a)

(vc)

(verify (assert (eq? (/ a a) 1)))
```
