### ISSUE TITLE
Interfacing with Rosette in other languages

### ISSUE THREAD

**Issue by femtomc** [emina/rosette#192]
Hi all!

I'm an avid Julia programmer -- whose native JIT compiler allows for the construction of stable APIs to libraries which provide C and C++ (for the most part) bindings.

I'm not exactly sure how this works in Racket -- but for DSLs like Rosette, is it possible to interface via C calls? I'm curious about calling to Rosette from Julia (which also supports a (mostly) hygienic macro system).

**Comment by emina** [comment]
Hi!  I don't have any experience doing this myself, but @lukenels and @xiw used Racket's FFI to interact with C code in one of their Rosette projects: https://github.com/uw-unsat/serval/tree/master/serval/llvm/capi 

In general, when interacting with solver-based systems and solvers themselves, my advice is to use pipes and a text-based interface.  This has the advantage of making it easy to terminate long-running processes and release all the resources cleanly.  It is, of course, slower than a native interface, but in these kinds of systems, that's usually not the bottleneck; the running time tends to be dominated by symbolic evaluation and solving time. 

Hope that helps!
