### ISSUE TITLE
Where is `asserts`?

### ISSUE THREAD

**Issue by chansey97** [emina/rosette#194]
Hi all!

I am reading the rosette tutorial from https://homes.cs.washington.edu/~emina/media/cav19-tutorial/part1.html

In the example code, the author used the `asserts` to exam the assertion store:

```
(asserts)         ; see the assertion stack
```

But I cannot find this identifier, `asserts: unbound identifier`?

Could someone help me? 

Thanks.

**Comment by emina** [comment]
The tutorial refers to Rosette 3.  

The latest version, Rosette 4, no longer supports `asserts`. 

Rosette 4 isn't backwards compatible with Rosette 3, so the tutorial won't translate exactly to the new version.

**Comment by chansey97** [comment]
Thanks.

But is there any way (e.g. idiom) to exam the assertion store in Rosette 4, just like `asserts` does?

**Comment by emina** [comment]
Yes, see [here](https://docs.racket-lang.org/rosette-guide/ch_essentials.html#%28part._sec~3aasserts%29) for an example.
