### ISSUE TITLE
Running `synthesize` examples diverged

### ISSUE THREAD

**Issue by chansey97** [emina/rosette#195]
Hi all,

I am reading the rosette tutorial from https://homes.cs.washington.edu/~emina/media/cav19-tutorial/part1.html

I run the [synthesize ](https://gist.github.com/emina/132db300dc39baa524606092a4312328#file-synthesize-rkt) example, but diverged (I waited for a long time but no result returned). 

The [synthax](https://gist.github.com/emina/132db300dc39baa524606092a4312328#file-synthax-rkt) example diverged as well.

Could someone help me? 
Thanks.

My environment:
Windows 7
Racket v8.0 [bc]
rosette v4 (latest version) 
rosette v3.2 also diverged

**Comment by chansey97** [comment]
I searched the issue-list and found a [solution](https://github.com/emina/rosette/issues/143#issuecomment-587319186) by @sorawee.

Following that solution, I set `(current-bitwidth 16)` , then the problem was solved. (I also noticed that the `current-bitwidth` parameteris set to #f by default in v3.x and v4.0. see the [release-notes](https://github.com/emina/rosette/blob/master/NOTES.md)).

Another workaround is to use [rosette v3.0](https://github.com/emina/rosette/tree/3.0).

There is no problem in rosette v3.0, although the `(current-bitwidth)` is `#f` in rosette v3.0 as well.

So I am not ensure this is a problem with `current-bitwidth`.

**Comment by emina** [comment]
As the previous posts points out, non-linear integer arithmetic is undecidable.  This is why the query doesn't return.  Different versions of Rosette may (and do) emit different formulas for the same query.  While the formulas have the same meaning, the syntactic differences can cause the solver to behave differently---especially on undecidable queries. 

I recommend reading the current Rosette Guide to learn more about Rosette, especially the [Essentials](https://docs.racket-lang.org/rosette-guide/ch_essentials.html) chapter.  The CAV tutorial was designed to work with older versions, which are no longer supported.

The Guide explains `current-bitwidth` in detail [here](https://docs.racket-lang.org/rosette-guide/ch_essentials.html#%28part._.Reasoning_.Precision%29) and [here](https://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_rosette.html#%28def._%28%28lib._rosette%2Fquery%2Ffinitize..rkt%29._current-bitwidth%29%29).
