### ISSUE TITLE
Unsoundness with quantifiers due to interaction with lexical scope, path conditions, and rewrite rules

### ISSUE THREAD

**Issue by anishathalye** [emina/rosette#196]
I think I found an unsoundness bug in Rosette's handling of quantifiers and the interaction between that, lexical scope, path conditions, and rewrite rules.

Here is an example of a buggy query, `x = t ∧ even x ∧ (∀x. ¬ (x = t ∧ odd x))`:

```racket
#lang rosette/safe

(define-symbolic* x t integer?)

(define q1
  (and
   (equal? x t)
   (even? x)
   (forall (list x) (not (and (equal? x t) (odd? x))))))

(solve (assert q1)) ; => (unsat)
```

This returns `(unsat)`, even though this query is satisfiable (e.g. `[x = 0; t = 0]`).

Renaming the `x` inside the forall into a `y`, we get a right answer:

```racket
(define-symbolic* y integer?)

(define q2
  (and
   (equal? x t)
   (even? x)
   (forall (list y) (not (and (equal? y t) (odd? y))))))

(solve (assert q2)) ; => (model [x 0] [t 0])
```

Introducing an intermediate variable for the forall also gives the right answer:

```racket
(define tmp (forall (list x) (not (and (equal? x t) (odd? x)))))

(define q3
  (and
   (equal? x t)
   (even? x)
   tmp))

(solve (assert q3)) ; => (model ...)
```

Similarly, using a hack to prevent Rosette's rewrite rules from (incorrectly, in this case) simplifying a term gives the right answer:

```racket
(define-symbolic* foo (bitvector 1))

;; returns e, but wrapped with some stuff to avoid simplification
(define (avoid-simplification e)
  (if (equal? (concat foo (bv 0 1)) (bv -1 2))
      #f ; unreachable
      e))

(define q4
  (and
   (equal? x t)
   (even? x)
   (forall (list x) (not (and (avoid-simplification (equal? x t)) (odd? x))))))

(solve (assert q4)) ; => (model ...)
```

I think what's going on in the test cases above is that the `(and ...)` (and similar forms, like `if`) append to `vc-assumes` when exploring the branches, and so `(equal? x t)` gets added to the `vc-assumes`, and then the `(equal? x t)` inside the forall, with its `x` bound by the quantifier, gets incorrectly simplified to a `#t`.

Also, I wanted to make sure I wasn't violating the spec of forall by using the same variable both bound in the forall and free in another part of the query, but I think this is supposed to be supported, unless I'm misinterpreting the docs:

> The usual lexical scoping rules apply to quantified symbolics; if body is a quantified formula over a variable v in vs, then the innermost quantification of v shadows any enclosing quantifications.

**Comment by emina** [comment]
Note that `forall` is a function and not a macro.  So, to evaluate `(forall vars expr)`, we first evaluate `vars` to get the variables to be quantified over, and we then evaluate `expr` to get the body of the quantified formula.  This means that `expr` is evaluated in the environment in which `forall` is evaluated; `forall` itself doesn't create an environment at evaluation time, but _after_ the formula is constructed. In other words, the scoping rules apply at the formula level.

So, `q1` is equivalent to this program, which makes the evaluation order and environment explicit:

```
#lang rosette/safe

(define-symbolic* x t integer?)

(define q1
  (and
   (equal? x t)
   (even? x)
   (let ([vars (list x)]
         [body (not (and (equal? x t) (odd? x)))])
   (forall vars body)))) 

(solve (assert q1)) 
```

In general, it's best to avoid evaluating anything in the body of quantified formulas.  I recommend pulling everything out into `let` bindings and using `with-vc` as needed to capture side effects.

**Comment by anishathalye** [comment]
Got it. Thank you for the clarification and quick response!
