### ISSUE TITLE
Use early return in rosette?

### ISSUE THREAD

**Issue by coqt** [emina/rosette#201]
I want to trigger some interesting exceptions only. In other terms, I want to put something like `(assert #f "trigger me please")` in that path, and Rosette can 'ignore' other ones.

I tried to use early return with call/cc, but it doesn't work:

```racket
#lang rosette

(define-symbolic x integer?)

(define-syntax define/return
  (lambda (x)
    (syntax-case x ()
      [(_ (name . args) . body)
       (with-syntax
         ([return (datum->syntax #'name 'return)])
        #'(define (name . args)
            (call/cc (lambda (return) . body))))])))

;; dumb example
;; I also tried to wrap the function with-exception-handlers and return -1 on the exception I care about
;; However, those kind of unsafe operations clearly don't play nicely with the SVM.

(define/return (find-x x)
  (cond
    [(= x 1) 0]
    [(= x 2) (return -1)]
    [else (return -2)]))

(solve (assert [= -2 (find-x x)]))
```

Could you provide some guidance?

**Comment by sorawee** [comment]
Yes, this is expected -- you are not supposed to use `call/cc` in Rosette, since it's not lifted to work with symbolic evaluation.

**Comment by coqt** [comment]
Thank you for confirming my assumption. Is there any way to achieve similar effect with Rosette?

**Comment by emina** [comment]
As @sorawee notes, Rosette lifts only structured control flow (`if` expressions and derivates), and it won't work with control constructs as such as `call/cc`.

If you need to reason about a language with `return` statements (or, more generally, `goto`s), there are two options.

(1)  Write an interpreter for the language in Rosette.  The interpreter itself can be written using structured control-flow, while interpreting `goto`s etc within the guest language.  See Figure 1 of [this paper](https://unsat.cs.washington.edu/papers/porncharoenwase-symfix.pdf) for a self-contained example (and see the entire section for avoiding some of the common performance bottlenecks in such interpreters).  This is the recommended approach for maximum control over the encoding.

(2) Write a shallow embedding of the language in Rosette, and macro-transform every procedure definition to store returned values into a designated variable, wrapping each expression with a guard that checks if that variable is set before proceeding.  [Here](https://github.com/mckaz/vmcai-rdl/blob/master/lib/rdl/verif_libraries/ivl.rkt) is an example of this second approach, also described in [this paper](https://homes.cs.washington.edu/~emina/doc/rtr.vmcai18.pdf).
