### ISSUE TITLE
Expanding the `define-grammar` and `choose` constructs

### ISSUE THREAD

**Issue by RafaeNoor** [emina/rosette#204]
Hello! 
I'm trying to modify the current implementation of `define-grammar` and `define-choose` into using another metric than the `#:depth`. The idea is that at the top level we would specify a cost budget as so:

```
(define (synth_def a b c)
   (synth_grammar a b c #:budget 30)
)
```

Each rule in the grammar would have a cost associated with it:

```
[expr (choose 
   a  #:cost 5
   b  #:cost 3
    ...
   (+ (expr) (expr)) #:cost 10
)]
```

Where as in the depth case the implementation is using `parameterize` to decrement the depth by 1 when moving on to the next level and doing `@assert` on the depth being greater than 0, I want to decrement the `budget` by the `#:cost _p` of each rule and the expansion checks if we have no exhausted the budget.

I have been trying to modify `rosette/lib/synthax.rkt` by adding these changes but I'm having difficulty interpreting some of the existing code. Could you point out how I should go about incorporating these changes (I'm not overriding the existing definitions but writing new constructs and exporting them to be used in my context).

**Comment by emina** [comment]
This can't be done for the following reason.  For the unrolling of the grammar to terminate, the termination condition must be concrete.  This is how the current implementation behaves:  the depth is decremented at each unrolling.  If different costs are assigned to each branch, and they are summed together, then the total cost of the AST is going to be symbolic.  If this symbolic value is used to decide whether to stop unrolling, the program will run forever. 

If you want to assign costs to symbolic ASTs, the best approach is use a deep embedding:  define the AST for your language using `struct`s; write an interpreter over those structs; write a procedure to generate a sketch / symbolic AST;  and, finally, ask the synthesizer to give you an AST that has some small cost.  

Here is an example:

```
#lang rosette

(require rosette/lib/destruct
         rosette/lib/angelic)

; Because we'll be using regs to index into a
; vector, it is best to make them mutable 
; so they get merged into a union rather than field-wise.
(struct reg (id)   #:transparent #:mutable)
(struct lit (val)  #:transparent)
(struct add (left right) #:transparent)


; Prog is an expression in the above AST.
; env is a vector of values; register
; identifiers must be in the range 0 ... |env| - 1.
(define (interpret prog env)
  (destruct prog
    [(reg id) (vector-ref env id)]
    [(lit val) val]
    [(add left right)
     (+ (interpret left env)
        (interpret right env))]))


(define (grammar vars #:depth k)
  (assert (> k 0))
  (cond
    [(choose* #t #f)
     (define-symbolic* val integer?)
     (lit val)]
    [(choose* #t #f)
     (apply choose* vars)]
    [else
     (add (grammar vars #:depth (- k 1))
          (grammar vars #:depth (- k 1)))]))

(define (cost expr)
  (destruct expr
    [(lit _) 3]
    [(reg _) 5]
    [(add left right)
     (+ 10 (cost left) (cost right))]))

(define-symbolic x y integer?)

(define env (vector x y))

; Get a sketch of depth 3.
(define sketch (grammar (list (reg 0) (reg 1)) #:depth 3))

; This sketch contains programs reg0 + 1 + 1 as well as reg0 + 2.
(define reg0+1+1
  (solve
   (assert
    (equal?
     sketch
     (add (reg 0) (add (lit 1) (lit 1)))))))
            
(evaluate sketch reg0+1+1)
; (add (reg 0) (add (lit 1) (lit 1)))
(cost (add (reg 0) (add (lit 1) (lit 1))))
; 31

(define reg0+2
  (solve
   (assert
    (equal?
     sketch
     (add (reg 0) (lit 2))))))
(evaluate sketch reg0+2)
; (add (reg 0) (lit 2))
(cost (add (reg 0) (lit 2)))
; 18

; Now, find a program of cost < 20 that adds 2 to reg0.
(define sol
  (synthesize
   #:forall env
   #:guarantee
   (begin
     (assert
      (equal?
       (interpret sketch env)
       (+ x 2)))
     (assert
      (< (cost sketch) 20)))))

(evaluate sketch sol)
;(add (lit 2) (reg 0))

```
