### ISSUE TITLE
Instructions to install rosette on Windows unclear / wrong?

### ISSUE THREAD

**Issue by ChrisJefferson** [emina/rosette#209]
Warning: I don't know anything about Racket, or Rosette, so apologises if this is wrong.

The instructions in "1 Getting started" say to run:

```
> raco pkg install rosette
```

But I can't seem to make that work. In Racket it tells me "raco: undefined;", on a windows terminal "raco" isn't a program that gets installed.

I can open "DrRacket" (which is mentioned further down), and that has a "Package Manager" option in the file menu, and when I typed "rosette" in there things seem to have been installed correctly and now work.

Another (minor) comment, on the first example of code (start of Section 2) maybe re-iterate that you need to write `#lang rosette/safe`, as DrRacket filled in ```#lang racket``` automatically, and it took me a while to realise I had to change it.

**Comment by emina** [comment]
`raco` is a command line distributed with Racket.  Depending on how you installed Racket, you might have to locate it on your system to call it.  Glad to hear that you get Rosette working :)
