### ISSUE TITLE
Using optimize with Boolector Solver?

### ISSUE THREAD

**Issue by RafaeNoor** [emina/rosette#211]
Hello, 
I was experimenting with using different backend SMT solvers (e.g. Z3 and Boolector). However when using the `Boolector` solver with `optimize` rosette construct, it says it's not supported where as it does work with `Z3`. Is there any (theoretical) reason why it isn't supported with Boolector. If not then I can try adding it's support. I know that Boolector does not support infinite precision integers hence I had to use the `current-bitwidth` to represent these as finite precision integers.

**Comment by emina** [comment]
The `optimize` construct works only with solvers that provide native support for optimization.  At this point, Z3 is the only one that does.
