### ISSUE TITLE
Verifier fails to read model

### ISSUE THREAD

**Issue by volisoft** [emina/rosette#213]
**OS** NixOS
**Platform** linux-aarch64
**Z3** version 4.8.14 - 64 bit
**DrRacket** version 8.3
**Rosette** 9d14d447d01013ddffde182cbe82dd79fecdc398

This test case is taken from the [Rosette tutorial](https://homes.cs.washington.edu/~emina/media/cav19-tutorial/part1.html).
```
(define (poly x)
 (+ (* x x x x) (* 6 x x x) (* 11 x x) (* 6 x)))
(define (fact x)
 (* x (+ x 1) (+ x 2) (+ x 2)))
(define (same p f x)
 (assert (= (p x) (f x))))
(define-symbolic i integer?)
(verify (same poly fact i))

X Error
read-solution: expected model, given ((define-fun c0 () Int (- 9)) (define-fun e10 () Bool (not (= (+ (* c0 c0 c0 c0) (* 6 c0 c0 c0) (* 11 c0 c0) (* 6 c0)) (* c0 (+ 1 c0) (+ 2 c0) (+ 2 c0))))) (define-fun e7 () Int (+ 2 c0)) (define-fun e2 () Int (* 6 c0 c0 c0)) (define-fun e5 () Int (+ (* c0 c0 c0 c0) (* 6 c0 c0 c0) (* 11 c0 c0) (* 6 c0))) (define-fun e3 () Int (* 11 c0 c0)) (define-fun e9 () Bool (= (+ (* c0 c0 c0 c0) (* 6 c0 c0 c0) (* 11 c0 c0) (* 6 c0)) (* c0 (+ 1 c0) (+ 2 c0) (+ 2 c0)))) (define-fun e1 () Int (* c0 c0 c0 c0)) (define-fun e6 () Int (+ 1 c0)) (define-fun e4 () Int (* 6 c0)) (define-fun e8 () Int (* c0 (+ 1 c0) (+ 2 c0) (+ 2 c0))))
> 
```

**Comment by emina** [comment]
I can't reproduce this on my machine (OS X) with Z3 version 4.8.8 - 64 bit.

It looks like the version of Z3 you're using is returning an invalid model.

I'd advise using version 4.8.8. This one should be automatically downloaded when you install Rosette (see [here](https://github.com/emina/rosette/blob/9d14d447d01013ddffde182cbe82dd79fecdc398/rosette/private/install.rkt#L47)).

**Comment by volisoft** [comment]
Thank you for quick response. I'll try to build Z3 version 4.8.8 for aarch64, since the one shipped with Rosette doesn't run on this platform (I assume it's built for x86_64)

**Comment by emina** [comment]
Hope it works!

I forgot to mention that this tutorial is out of date.  While parts of it should still work in Rosette 4, it was developed for Rosette 3.  For Rosette 4, [Chapter 2](https://docs.racket-lang.org/rosette-guide/ch_essentials.html) of the Rosette Guide is a better resource.

**Comment by volisoft** [comment]
Just checked with Z3 version 4.8.8 and it works as expected. Thank you so much for help and for pointing to the updated documentation.
