### ISSUE TITLE
Error: application: not a procedure;

### ISSUE THREAD

**Issue by VioletLi** [emina/rosette#214]
Hello,

I'm sorry to bother you, but I just started using Racket and I don't know where to go for help……

I want to use Rosette to synthesize some program by IO example, and create some functions to represent IO examples like this:
```
(define (test3 impl a b)
  (assert (or (not (and (= a 96)
                        (= b 86)))
              (= (impl a b) 91))))
```
and then I try to synthesize the function like this
```
(define sol
  (synthesize
   #:forall (list info1 info2)
   #:guarantee (and (test1 func1 info1 info2) (and (test2 func1 info1 info2) (test3 func1 info1 info2)))))
```
but I get an error
```
application: not a procedure;
 expected a procedure that can be applied to arguments
  given: (unknown)
```
and I have no idea what goes wrong. Where does this "unknown" come from?

Thank you very much!!!

**Comment by emina** [comment]
This means that your program is using an undecidable theory (I'm guessing non-linear integer arithmetic), and Z3 is unable to find a solution.  In that case, it returns "unknown". 

In general, it's best to stay away from using unbounded (mathematical) integers it at all possible, and use finite-precision integers (bitvectors) instead. 

The easiest way to switch from unbounded integers to finite-precision ones is to set the [current-bitwidth](https://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_rosette.html#%28def._%28%28lib._rosette%2Fquery%2Ffinitize..rkt%29._current-bitwidth%29%29) parameter to the desired precision:

```
(current-bitwidth 32) ; use 32 bits to represent integers
```

If you are solving for a program that satisfies a set of concrete IO examples, you don't need to use the `synthesize` query, which is expensive.  You can use the [`solve`](https://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_rosette.html#%28form._%28%28lib._rosette%2Fquery%2Fform..rkt%29._solve%29%29) query instead:

```
(solve
 (assert
  (and (= (impl 96 86) 91) (= (impl 1 2) 3)))) ; solve for 2 IO examples
```


[Chapter 2](https://docs.racket-lang.org/rosette-guide/ch_essentials.html) of the Rosette guide describes all of this in more detail.
