### ISSUE TITLE
Raising hard errors

### ISSUE THREAD

**Issue by rachitnigam** [emina/rosette#215]
My understanding is that if a symbolic branch throws an error in Rosette, the evaluation marks that path as infeasible. However, sometimes I need to signal to the user that the error occurred because the input way malformed in some manner. Is there a way to throw hard errors like this? 

I've seen the [documentation recommendation](https://docs.racket-lang.org/rosette-guide/ch_error-tracing.html#%28part._sec~3aerrors-under-queries%29) as well as the error tracer but my system mostly interacts with the command line and I'd like to have the system emit errors when a malformed input is encountered.

**Comment by sorawee** [comment]
Would printing the error and then `(exit 1)` work for you? The invoker can then observe the exit code if there's an error.

**Comment by quangIO** [comment]
I believe Rosette only swallow `exn:fail?` so raising something like `exn:fatal` should work

**Comment by rachitnigam** [comment]
Is `exn:fatal` already defined by racket somewhere? I couldn't find it in the docs.

**Comment by sorawee** [comment]
No, you need to make one. Perhaps something like this:

```
#lang rosette

(struct exn:fatal exn ())

(define-symbolic b boolean?)

(when b
  (raise (exn:fatal "bye" (current-continuation-marks))))
```

This is a good approach if you need to be able to handle the exception programmatically with `with-handlers`. But otherwise, `(exit 1)` might be a bit simpler (and doesn't produce a stacktrace, which might not might not be what you want).
