### ISSUE TITLE
Provide Docker image

### ISSUE THREAD

**Issue by Niols** [emina/rosette#217]
Hey there,

In some work of [Hachi](https://github.com/HachiSecurity/), we are relying on Rosette, which we then ship with our tooling. This involves some Docker work, and I was wondering whether you would be interested in having a Docker image (containing basically just Racket, Rosette's dependencies and Rosette) defined and maintained in this repository. I would happily propose a PR in that case.

Best,
Niols

**Comment by lukenels** [comment]
Hi Niols,

That sound awesome, and would definitely be of use to myself and others! A couple of quick questions about what you intend to do before moving forward:

- Where would the Docker image be hosted? On GitHub or on a third party registry like DockerHub? We have an organizational account for [GitHub] and [DockerHub] that we could use to host the image on.
- Is it possible to have the image automatically build and push whenever someone commits to this repository? The goal would be to eliminate the need for us to maintain the Dockerfile as changes are made to Rosette and the need to manually push. Perhaps GitHub Actions can be of use, but I'm not familiar enough with them to say. 
- What distribution were you planning on basing the image on? I have a couple of examples of simple Dockerfiles that install Rosette on top of [ubuntu] and [alpine] that I've used for other projects. You could use one of these as a basis for yours (of course after cleaning things up by avoiding hard-coding the Rosette version, removing non-Rosette related packages, etc.) Alpine will be smaller but perhaps not as compatible with other software as Ubuntu. Curious what you think.

Let me know if you have any other questions or need us to do any admin things to enable this. 😄 

[GitHub]: https://github.com/uw-unsat
[DockerHub]: https://hub.docker.com/u/unsat
[alpine]: https://github.com/uw-unsat/exoverifier/blob/da64f040db04614be81d9d465179fa3e0e2cd0c4/scripts/Dockerfile
[ubuntu]: https://github.com/uw-unsat/serval/blob/72adc4952a1e62330aea527214a26bd0c09cbd05/scripts/Dockerfile

**Comment by Niols** [comment]
Hi Luke!

> Where would the Docker image be hosted? On [GitHub](https://github.com/uw-unsat) or on a third party registry like [DockerHub](https://hub.docker.com/u/unsat)? We have an organizational account for GitHub and DockerHub that we could use to host the image on.

I do think it is nice to host the image on a registry so that people can build on top of it with a simple `FROM .../rosette`. I don't have a particular preference between [GitHub Packages](ghcr.io) or [Docker Hub](http://hub.docker.com). The former would have the images under `ghcr.io/emina/rosette` while the latter could allow you to have `emina/rosette` (the `rosette` user seems taken already). It could also be somewhere else if you have something particular in mind.

> Is it possible to have the image automatically build and push whenever someone commits to this repository? The goal would be to eliminate the need for us to maintain the Dockerfile as changes are made to Rosette and the need to manually push. Perhaps GitHub Actions can be of use, but I'm not familiar enough with them to say.

Definitely! That is something I usually do through GitHub Actions and I can provide that in a PR as well. At the very least, we should push each release with their own tag, but it is also possible to push `main`, or even all the branches. Depending on the choice, one might want a different semantics for the `latest` tag: it could be the latest stable release or the latest working commit on `main`.

> What distribution were you planning on basing the image on? I have a couple of examples of simple Dockerfiles that install Rosette on top of [ubuntu](https://github.com/uw-unsat/serval/blob/72adc4952a1e62330aea527214a26bd0c09cbd05/scripts/Dockerfile) and [alpine](https://github.com/uw-unsat/exoverifier/blob/da64f040db04614be81d9d465179fa3e0e2cd0c4/scripts/Dockerfile) that I've used for other projects. You could use one of these as a basis for yours (of course after cleaning things up by avoiding hard-coding the Rosette version, removing non-Rosette related packages, etc.) Alpine will be smaller but perhaps not as compatible with other software as Ubuntu. Curious what you think.

I tend to base my images on top of Alpine in order to get a smaller footprint. Another upside of Alpine (irrelevant to Racket, but I'll still put it here) that I particularly enjoy is that its linker supports static linking of everything, so I sometimes use it to build fully statically-linked executables for an even smaller footprint: install all the dependencies in an Alpine container, build the executable, put it in another raw Alpine container (without all the dependencies in particular) and you're good to go. I usually find Alpine satisfactory and compatible with pretty much all I need it for.

I would also be fine building on top of Debian/Ubuntu. Another option (which I have been using so far for my Racket projects) would be to base ourselves on [Docker Hub's racket/racket images](https://hub.docker.com/r/racket/racket). They are not technically “official” Racket images but they are maintained by [Jack Firth](https://github.com/jackfirth). They are based on Debian (and its `stable-slim` tag specifically). 

I do not have strong feelings about this, so if you do, I'll happily follow them. Otherwise, I would probably go for Jack Firth's images: them being based on Debian should make them rather compatible with other software, and that would make for very simple Dockerfiles to maintain on Rosette's side.

> Let me know if you have any other questions or need us to do any admin things to enable this. :smile: 

No particular questions from my side. I will probably need you at some point to set up a secret token to log in to the Docker registry that we choose, but I think that would be all.

**Comment by lukenels** [comment]
> I do think it is nice to host the image on a registry so that people can build on top of it with a simple `FROM .../rosette`. I don't have a particular preference between [GitHub Packages](ghcr.io) or [Docker Hub](http://hub.docker.com). The former would have the images under `ghcr.io/emina/rosette` while the latter could allow you to have `emina/rosette` (the `rosette` user seems taken already). It could also be somewhere else if you have something particular in mind.

Sounds good! I think using GitHub Packages (`ghcr.io/emina/rosette`) makes more sense to minimize the number of different accounts we would need to have and maintain.

> Definitely! That is something I usually do through GitHub Actions and I can provide that in a PR as well. At the very least, we should push each release with their own tag, but it is also possible to push `main`, or even all the branches. Depending on the choice, one might want a different semantics for the `latest` tag: it could be the latest stable release or the latest working commit on `main`.

I'm a fan of having each tagged commit / release in git associated with a tagged image and also having a `latest` tag for the most recent commit to `master` / `main`.

> I tend to base my images on top of Alpine in order to get a smaller footprint. Another upside of Alpine (irrelevant to Racket, but I'll still put it here) that I particularly enjoy is that its linker supports static linking of everything, so I sometimes use it to build fully statically-linked executables for an even smaller footprint: install all the dependencies in an Alpine container, build the executable, put it in another raw Alpine container (without all the dependencies in particular) and you're good to go. I usually find Alpine satisfactory and compatible with pretty much all I need it for.
> 
> I would also be fine building on top of Debian/Ubuntu. Another option (which I have been using so far for my Racket projects) would be to base ourselves on [Docker Hub's racket/racket images](https://hub.docker.com/r/racket/racket). They are not technically “official” Racket images but they are maintained by [Jack Firth](https://github.com/jackfirth). They are based on Debian (and its `stable-slim` tag specifically).
> 
> I do not have strong feelings about this, so if you do, I'll happily follow them. Otherwise, I would probably go for Jack Firth's images: them being based on Debian should make them rather compatible with other software, and that would make for very simple Dockerfiles to maintain on Rosette's side.

I have no strong feelings here either. Sounds like using Jack's images will simplify updating Racket versions so I'm okay with going with that.

> No particular questions from my side. I will probably need you at some point to set up a secret token to log in to the Docker registry that we choose, but I think that would be all.

Sounds good, I can coordinate with @emina to facilitate this once we get to that point. Feel free to submit a PR for the Dockerfile and the GitHub Actions and I'll take a look.

Thanks!

**Comment by Niols** [comment]
> I have no strong feelings here either. Sounds like using Jack's images will simplify updating Racket versions so I'm okay with going with that.

The main difference would be at the beginning of the Dockerfile and in the speed at which the Docker image would be built.

### Option 1: Jack's Images

The Dockerfile simply starts with:

```
FROM racket/racket:8.3
```

Updating Racket's version is only a matter of updating the tag of the image, provided that the tag has been made available.

### Option 2: Alpine-based Images

The Dockerfile starts with something such as:

```
FROM alpine:3.15
ARG RACKET_VERSION=8.4
ARG RACKET_VARIANT=cs
RUN apk add --no-cache gcompat
RUN wget "https://mirror.racket-lang.org/installers/${RACKET_VERSION}/racket-minimal-${RACKET_VERSION}-x86_64-linux-${RACKET_VARIANT}.sh"
RUN echo 'yes\n1\n' | sh racket-minimal-${RACKET_VERSION}-x86_64-linux-${RACKET_VARIANT}.sh --create-dir --unix-style --dest /usr/
RUN rm racket-minimal-${RACKET_VERSION}-x86_64-linux-${RACKET_VARIANT}.sh
RUN raco setup --no-docs
```

(In an actual Dockerfile, I would add comments to those steps.)

Updating Racket's version is only a matter of updating the `RACKET_VERSION` line in the Dockerfile.

### Comparison

On my laptop with a decent internet connection, it takes 23s to build the Alpine-based image containing Racket, most of which is used to download the Racket installer. Downloading and extracting Jack's images only takes about 7s.

The Alpine-based image containing Racket (*not* Rosette at this point) weighs 163MB while Jack's weighs 237MB. All the difference comes from the difference between Alpine (6MB) and Debian Slim (80MB).

Because Rosette's Z3 relies on `libstdc++` and `libgcc` (I did not find a way to have it run on Musl but maybe there is?), those would have to be additionally installed in the Alpine image, which is arguably not the cleanest but only changes the above number by 4MB.

I would argue that Alpine's version is actually not harder to maintain: I don't think that the Dockerfile becomes harder to read; if anything, it makes explicit the way Racket is installed which should make future changes easier to follow. Additionally, it removes a dependency on Jack's images (I am not expecting them to be discontinued any time soon, but who know).

I will propose a PR in the coming days, probably based on Alpine unless you ask me otherwise!

**Comment by lukenels** [comment]
Hi Nicolas,

Sounds good! I'm a fan of using Alpine for the same reasons you stated 👍 I don't think there's a way to avoid adding `libstdc++` and `libgcc` but those are so small it shouldn't matter. And not depending on a 3rd-party image other than Alpine will help maintenance in the future. Thanks!
