### ISSUE TITLE
It is possible to get a symbolic's solution without assertion?

### ISSUE THREAD

**Issue by chansey97** [emina/rosette#225]
For example, following program returns symbolic `a` itself:

```
#lang rosette

(define-symbolic a integer?)
(let ((sol (solve (assert #t))))  
  (evaluate a sol))
;; => a
```

But I want (at least a random number) `0`.

From SMT perspective, it can return a concrete value:

```
(declare-const a Int)
(check-sat)
sat
(get-model)
(
  (define-fun a () Int 0)
)
``` 

I once tried to use `equal?` to add a meaningless assertion, but rosette will simplify it to `#t`, so it is useless.

```
(define-symbolic a integer?)
(equal? a a)
;; => #t
```

It there a way to get a symbolic's solution without assertion?

Thanks.

**Comment by sorawee** [comment]
This is an intended behavior. You can use [`complete-solution`](https://docs.racket-lang.org/rosette-guide/sec_solvers-and-solutions.html#%28def._%28%28lib._rosette%2Fsolver%2Fsolution..rkt%29._complete-solution%29%29) to fill in "missing" bindings.

**Comment by chansey97** [comment]
@sorawee Thanks!
