### ISSUE TITLE
How to use the code produced by generate-forms?

### ISSUE THREAD

**Issue by nano-o** [emina/rosette#226]
Hello, I was hoping to use `generate-forms` as part of a macro in order to use the synthesized code in my programs.
However, on my system, `generate-forms` produces syntax objects that have no binding information.
E.g. in the following, `bv-code` looks like `(define my-bv (bv #x00000001 32))` but identifiers like `define` or `bv` have no binding information attached.
I am doing something wrong? If not, what's the intended use of the syntax object produced by `generate-forms`?
```
#lang rosette
(require
  rosette/lib/synthax
  (for-template racket/base (only-in rosette bv)))
(define-grammar (g)
  (bv-rule (?? (bitvector 32))))
(define my-bv (g))
(define s
  (solve (assume
          (equal? my-bv (bv 1 32)))))
(define bv-code
  (car (generate-forms s)))
```

**Comment by emina** [comment]
You aren’t doing anything wrong.  This form generates the syntax object but is not intended to be used in a macro.  Most applications just print the form.  It is possible to turn the generated form into code using Racket’s `eval` and setting up the namespace with the right bindings. [Here](https://github.com/emina/rosette/blob/master/test/query/synthax.rkt#L61) is an example from Rosette’s unit test suite.

**Comment by nano-o** [comment]
Thanks for the quick response! I'll study the linked example.
