### ISSUE TITLE
branches are not supported when constructing bitvectors

### ISSUE THREAD

**Issue by QDelta** [emina/rosette#235]
The following code will fail:
```racket
#lang rosette/safe
(define-symbolic b boolean?)
(bv (if b 1 2) 32)
```
The error message:
```
[assert] bv: expected a real, non-infinite, non-NaN number
  value: (ite b 1 2)
```
The expected result:
```
(ite b (bv #x00000001 32) (bv #x00000002 32))
```

I noticed that `bv` only accepts concrete values (`real?`). Is there a solution or a workaround (like implementing a `bv` wrapper)? It may be difficult for me to just replace all integers with bitvectors.

**Comment by anishathalye** [comment]
You want [integer->bitvector](https://docs.racket-lang.org/rosette-guide/sec_bitvectors.html#%28def._%28%28lib._rosette%2Fbase%2Fbase..rkt%29._integer-~3ebitvector%29%29), which works on symbolic values.

```racket
(define-symbolic* b boolean?)
(integer->bitvector (if b 1 2) (bitvector 32))
```

**Comment by QDelta** [comment]
> You want [integer->bitvector](https://docs.racket-lang.org/rosette-guide/sec_bitvectors.html#%28def._%28%28lib._rosette%2Fbase%2Fbase..rkt%29._integer-~3ebitvector%29%29), which works on symbolic values.
> 
> ```racket
> (define-symbolic* b boolean?)
> (integer->bitvector (if b 1 2) (bitvector 32))
> ```

That's exactly what I want, thank you!
