### ISSUE TITLE
Call/cc support?

### ISSUE THREAD

**Issue by jnear** [emina/rosette#259]
I'm interested in modeling control-flow constructs like switch and return in C. This is easy to do with call/cc, but it's not clear that call/cc is supported (at least in Rosette/safe). Is call/cc supported in Rosette, or is there some other trick for implementing operators that affect control flow? Thanks!

**Comment by emina** [comment]
Rosette doesn't support unstructured control flow (such as returns and call/cc). 

But you can implement it with the existing constructs. 

See [here](https://github.com/mckaz/vmcai-rdl/blob/master/lib/rdl/verif_libraries/ivl.rkt) for an example that uses a shallow embedding, and [here](https://unsat.cs.washington.edu/papers/nelson-serval.pdf) for an example that uses a deep embedding.

A shallow embedding is easier to implement, but a deep embedding gives you better control over the performance of the symbolic evaluator (merging/splitting with for/all).

**Comment by jnear** [comment]
Awesome - thanks very much!!
