### ISSUE TITLE
unsound behavior?

### ISSUE THREAD

**Issue by stchang** [emina/rosette#36]
This example:
```racket
(list
 (add1 (if b 1 (bv 1 1)))
 (bvnot (if b 1 (bv 1 1))))
```
evaluates to `(list 2 (bv 0 1))` even though it would result in an exception in Racket for any value of `b`. Is this the intended behavior?

**Comment by emina** [comment]
This is sound behavior.  

To see why, we need to examine the assertion stack after this point:

```
> (define-symbolic b boolean?)
> (list
   (add1 (if b 1 (bv 1 1)))
   (bvnot (if b 1 (bv 1 1))))
'(2 (bv 0 1))
> (asserts)
'((! b) b)
```

Observe that Rosette has generated two assertions that can never be simultaneously satisfied.  So, if we ask for a non-failing execution of this program, we'll get no solution:

```
; first, clear asserts since they are treated as preconditions otherwise, 
; as documented for solve/verify forms
> (clear-asserts!) 
> (solve (list
        (add1 (if b 1 (bv 1 1)))
        (bvnot (if b 1 (bv 1 1)))))
(unsat)
```
But if we try to verify the program, we'll get an empty counterexample, indicating that any value of `b` leads to an error:

```
> (verify (list
         (add1 (if b 1 (bv 1 1)))
         (bvnot (if b 1 (bv 1 1)))))
(model)
```

**Comment by stchang** [comment]
Thanks for the explanation.

Is it accurate to say that the result of symbolic evaluation is irrelevant when the assertions cannot be satisfied?

**Comment by emina** [comment]
That's accurate.

Another way to look at is that the assertions encode all possible ways to reach the current program state.  So, if the assertions are unsatisfiable, then the current program state is unreachable / infeasible.

**Comment by stchang** [comment]
That makes sense. 

As a somewhat related question, how often do Rosette programmers utilize Rosette's pruning of invalidly-typed branches?

For example, a traditional type checker (as in Typed Racket) would reject this program:
```racket
(define-symbolic b boolean?)
(add1 (if b 1 "one"))
```
but it is an acceptable Rosette program.

Would it help or burden Rosette programmers if a Typed Rosette rejected the program?

(More generally, we are trying to figure out what kinds of errors a Typed Rosette might want to focus on.)

**Comment by emina** [comment]
That's a very good question.
 
My understanding is that the most common / frustrating source of errors is accidentally calling library functions (say, `map`) incorrectly, and then having this error suppressed (in an unsatisfiable assertion) until solve-time.  

Rosette allows this example because Racket allows it as well.  The main design principle behind Rosette has been to try and implement Racket's semantics whenever possible.  (This is not always possible, and those cases are documented as such.)

Given that, I think it would make sense for a Typed Rosette to behave like Typed Racket.  Essentially, one could think of Typed Rosette as a macro-based "reimplementation" of Rosette, by analogy to Typed Racket and Racket.

**Comment by stchang** [comment]
That is helpful guidance. Thanks.

**Comment by AlexKnauth** [comment]
I think it would be helpful to distinguish between assertions and type errors. 

So this program would pass the type-checker and generate an assertion at run-time:
```racket
(define-symbolic b boolean?)
(assert (integer? (if b 1 "one")))
```
But this program would be a type error at compile time:
```racket
(define-symbolic b boolean?)
(add1 (if b 1 "one"))
```
In typed racket, applying `add1` to something that would be either an integer or a string would be type errors. But to make it easier to take advantage of Rosette's assertion behavior, programmers can always turn type errors into assertions by inserting a `cast` form:
```racket
(define-symbolic b boolean?)
(add1 (cast (if b 1 "one") Int))
```
This would pass the type-checker, and when run, it would produce `2` while generating the assertion that `b` is true.

Does that some reasonable and useful?

**Comment by emina** [comment]
This seems reasonable to me.  Essentially, if the type system is too conservative to admit a program that is correct, one could use assertions and the solver to discharge this proof.
