### ISSUE TITLE
user annotations to help Rosette's path merging?

### ISSUE THREAD

**Issue by stchang** [emina/rosette#39]
Would an `assert`-like form that returns a value be useful to Rosette programmers? It would return the value that the programmer annotates, but with some paths pruned using the additional information. 

A hypothetical `assert-pred` would behave like:
```racket
(define-symbolic b1 b2 boolean?)
(define-symbolic i1 i2 integer?)
(assert-pred i1 positive?) ; => i1, with (< 0 i1) added to the assertion store
(assert-pred (if b1 i2 b2) integer?) ; => i2, with b1 added to the assertion store
```
There are no paths to merge in the first `assert-pred`, but the second `assert-pred` eliminates the `b2` branch. Essentially, `assert-pred` allows programmers to help Rosette's path merging (if possible), at a higher point in the tree.

Does Rosette already support something like this? Would Rosette programmers ever want such an optimization?

**Comment by emina** [comment]
Rosette doesn't support a construct like this.  I personally haven't needed something of this sort, though I'm not sure if others have.  As one data point, no one has asked for this functionality before (and users have asked for other features that have implemented recently :).

Normally, early pruning is most useful when it enables more aggressive partial evaluation.  For example, the two expressions below are semantically equivalent, but the second one is more efficient from the point of view of partial evaluation:

```
#lang rosette

(define-symbolic i integer?)

(if (= i 1) (+ i 2) (+ i 3))

(if (= i 1) (+ 1 2) (+ i 3))
```

Of course, the above effect (of essentially replacing `i` with `1` in the `then` branch) is more significant in real code.

**Comment by AlexKnauth** [comment]
I think this would be useful for me. In normal racket code, I often start with some expression, and then later I want to add a side effect with it that depends on the value of the expression. So starting with 
```racket
(context (some-computation))
```
And then adding the side effect *without* messing up the return value:
```racket
(context (let ([x (some-computation)]) (side-effect x) x)
```
This pattern has come up when printf-debugging, memoizing, and error-checking. 
```racket
(context (let ([x (some-computation)]) (printf "(some-computation) = ~v\n" x) x))
(context (let ([x (some-computation)]) (hash-set! hsh input x) x))
(context (let ([x (some-computation)]) (unless (valid-value? x) (error ....)) x))
```
In typed racket, the error-checking is handled by its `assert` form, which turns `(assert (some-computation) valid-value?)` into something like the above.

I'm seeing the same thing in Rosette. Whenever I want to assert something about a return value, I have to put it in a `let`, treat `assert` like the side-effect above, and then return `x` explicitly. 
```racket
(context (let ([x (some-computation)]) (assert (valid-value? x)) x))
```
I would like to be able to express this in a better way.

**Comment by emina** [comment]
Since this is easy to achieve with an external macro, we'll leave it up users to define their own constructs of this form :)  

Our overall design goal is to keep the base language minimal, extending it only when a given feature cannot be implemented otherwise.  Language extensions are usually needed to add a new primitive symbolic datatype (e.g., integer? and real? recently), or expose access to a feature of the underlying solver (e.g., quantifiers or the distinct? predicate).

**Comment by AlexKnauth** [comment]
The part of this that can't be implemented otherwise is the branch-pruning optimizations that @stchang was talking about

**Comment by emina** [comment]
Many type-based optimizations can be achieved with `type-cast`:

```
#lang rosette

(define-symbolic b1 b2 boolean?)
(define-symbolic i1 i2 integer?)

> (type-cast integer? (if b1 i2 b2))
i2
> (asserts)
(list b1)
```

The more general optimizations I mentioned above would need more than `assert-pred`; they would require rewriting `if` expressions.

**Comment by AlexKnauth** [comment]
Oh, okay. It's a bit less general, but it might be what we wanted, since typed rosette will often be dealing with predicates that are `type?`. I can't find the documentation though; is it an unstable feature?

**Comment by emina** [comment]
It's not unstable, but it's internal to the implementation, so not something users necessarily want to see / use.  You'd need to know about this if you were implementing a new primitive type, for example.  

The interface is defined in

https://github.com/emina/rosette/blob/master/rosette/base/core/type.rkt

An example implementation is in

https://github.com/emina/rosette/blob/master/rosette/base/core/real.rkt#L36

Implementations of lifted primitive operators tend to make heavy use of `type-cast` to emit required runtime type checks.

**Comment by stchang** [comment]
Thanks, that's really helpful to know!

**Comment by AlexKnauth** [comment]
`cast-type` seems to be exactly what we needed! Thanks for pointing us to it.

**Comment by emina** [comment]
Awesome!  Anytime :)
