### ISSUE TITLE
query/debug behaves badly with make-variable-like-transformer

### ISSUE THREAD

**Issue by AlexKnauth** [emina/rosette#40]
If I run a program like this:
```racket
#lang rosette/safe
(require rosette/query/debug rosette/lib/render
         (for-syntax syntax/transformer))

(define-syntax add (make-variable-like-transformer #'+))
(define-syntax mult (make-variable-like-transformer #'*))

(define (poly x)
  (add (mult x x x x) (mult 6 x x x) (mult 11 x x) (mult 6 x)))

(define/debug (factored x)
  (mult x (add x 1) (add x 2) (add x 2)))

(define (same p f x)
  (assert (= (p x) (f x))))

(define ucore (debug [integer?] (same poly factored 12)))
(render ucore)
```
Rosette tries to render something in the definition of `make-variable-like-transformer` instead of the definition of the `factored` function in `define/debug`.

**Comment by emina** [comment]
The `make-variable-like-transfomer` is not in the safe / supported subset of the language.  So, by requiring it, you are essentially in the unsafe zone where things can and do go badly :)   

In general, rendering or form printing for debugging and synthesis will not work through user-defined macros.  It will, however, work through procedures, e.g.:

```
#lang rosette/safe
(require rosette/query/debug rosette/lib/render
         (for-syntax syntax/transformer))

(define (add . args) (apply + args))
(define (mult . args) (apply * args))

(define (poly x)
  (add (mult x x x x) (mult 6 x x x) (mult 11 x x) (mult 6 x)))

(define/debug (factored x)
  (mult x (add x 1) (add x 2) (add x 2)))

(define (same p f x)
  (assert (= (p x) (f x))))

(define ucore (debug [integer?] (same poly factored 12)))
(render ucore)
```

**Comment by AlexKnauth** [comment]
The typed rosette language we're working on uses our own version of `make-variable-like-transformer` just to assign types to functions. (That's where we ran into this.)

**Comment by AlexKnauth** [comment]
We experimented with a few things other than `proc` to put here:
https://github.com/emina/rosette/blob/master/rosette/query/debug.rkt#L38

For example if we replaced that with a syntax object that had the source location of the outer `stx` form, some things worked better. Is there a reason why it would be `proc` and not something else?

**Comment by emina** [comment]
In the examples we've tried in the (really distant) past, `proc` seemed to have source information attached to it more often than `stx`.  That is, the old version of Rosette would occasionally discard source information when it wasn't supposed to.  But that was ages ago, so perhaps that's no longer an issue.

The most involved example of debugging is this:

https://github.com/emina/rosette/blob/master/sdsl/fsm/demo.rkt

If it works the same with `stx` as with `proc`, it's probably fine to use `stx`.

**Comment by AlexKnauth** [comment]
Should I submit a pull request to change it?

**Comment by emina** [comment]
Sure, if the FSM demo works as expected, go for it (and, of course, the few `debug` tests pass :)

**Comment by stchang** [comment]
> the source location of the outer `stx`

Does this fix our problem? Didn't we already try it?

**Comment by AlexKnauth** [comment]
(No, we get the tainting problem either way.)

**Comment by stchang** [comment]
Ok. I guess `stx` does make more sense here.
