### ISSUE TITLE
xor broken?

### ISSUE THREAD

**Issue by stchang** [emina/rosette#44]
I think there might be a problem with `xor`. Is it supposed to allow non-booleans?

```racket
> (xor 11 #t)
(! 11)
> (xor 11 #f)
. . rosette/rosette/base/core/term.rkt:67:0: term-ord: contract violation
  expected: term?
  given: 11
```

**Comment by emina** [comment]
This is a bug.  I've pushed a fix that makes 'xor' behave the same as in Racket (so allowing non-booleans).
