### ISSUE TITLE
synthesize: specification and semantics mismatch

### ISSUE THREAD

**Issue by stchang** [emina/rosette#45]
The documentation for `synthesize` specifies a list of constants as the `#:forall` expression, but arbitrary expressions seem to be allowed.

```racket
#lang rosette
(define-symbolic x c integer?)
(synthesize #:forall (list 1) ;; should this error?
                   #:guarantee (assert (odd? (+ x c))))
```

Should the contract in the documentation be enforced?

**Comment by emina** [comment]
Arbitrary expressions are allowed though the most common use case is to explicitly provide a list of constants.  If the program provides a value that (transitively) includes no symbolic constants, then the outermost universal quantification is essentially a no-op.

**Comment by stchang** [comment]
Ok thanks. Should the documentation be updated? I can submit a pull request.

**Comment by emina** [comment]
Let's leave the documentation as-is for now.  I'm not yet sure that it's a good idea to advertise the existence of this functionality (i.e., providing anything but a list of symbolic constants in #:forall :)
