### ISSUE TITLE
Question: solution returned by `solve` changes based on unrelated expressions in program?

### ISSUE THREAD

**Issue by stchang** [emina/rosette#46]
This is more of a question rather than an issue.

The following example, derived from the example at the beginning of Sec 4.4 of the guide, produces a different result depending on whether the `(f 1)` is commented or uncommented:
```racket
#lang rosette
(define-symbolic f (~> integer? boolean?))
(define-symbolic x integer?)
(f 1) ; the existence of this expression changes the solver output
(define sol
  (solve
   (assert
    (not (equal? (f x) (f 1))))))
(define g (evaluate f sol))
(g x) ; (= 0 x) vs (= 1 x)
```

I realize that `solve` may produce any satisfactory result, but I can't figure out how the `(f 1)` above affects the solver output. Is there some state that is changed? (The assertion store seems to be unchanged.)

This behavior is somewhat problematic for us because it complicates unit testing.

**Comment by emina** [comment]
Yes, creating any symbolic value, regardless of whether it propagates to the final assertion store or not, affects the `term-cache`.  Symbolic terms are cached and also assigned a unique ID, which depends on the order in which they are created.  This, in turn, affects the order in which the final assertions are encoded---and that order affects the solution.  The solver is deterministic as long as the encodings are identical.  Rosette produces identical encodings only for identical runs of the same program. 

```
#lang rosette

(define-symbolic f (~> integer? boolean?))
(define-symbolic x integer?)
(f 1) ; the existence of this expression changes the solver output
(term-cache) ; contents of the term cache are affected by the above line
(define sol
  (solve
   (assert
    (not (equal? (f x) (f 1))))))
(define g (evaluate f sol))
(g x) ; (= 0 x) vs (= 1 x)
```

**Comment by stchang** [comment]
Ah, thank you. That's what we were looking for.
