### ISSUE TITLE
Quasiquote and length don't work well together

### ISSUE THREAD

**Issue by rohinmshah** [emina/rosette#47]
`quasiquote` can sometimes create symbolic lists that you can't take the `length` of. This seems to be an issue specifically when the symbolic list is represented as a pair with For example:
<pre>(define-symbolic b boolean?)
(define sym-list (if b '(bar) '(bar baz)))
(define thing `(foo ,@sym-list))
(print thing) (newline)
(print (length thing)) (newline)</pre>
prints:
<pre>'(foo . {[b (bar)] [(! b) (bar baz)]})
length: contract violation
  expected: #<procedure:list?>
  given: '(foo . {[b (bar)] [(! b) (bar baz)]})
  context...:
   @length
   /.../tmp.rkt: [running body]</pre>
While this throws an error, I also have a much larger codebase where it just returns the wrong result (it says the length is definitely 2 when I'm fairly confident it should be either 3 or 4). I haven't been able to create a smaller example showing this behavior.

This code works fine if you replace the `quasiquote` with `(cons 'foo sym-list)`, producing the output:
<pre>{[b '(foo bar)] [(! b) '(foo bar baz)]}
(ite b 2 3)</pre>

So it looks like `length` can only work with symbolic lists which are not represented with dotted-tail notation (that is, as a pair with a symbolic `car` and symbolic `cdr`). So far I've only been able to construct such a symbolic list with `quasiquote`.

I noticed that there's no definition of `quasiquote` in Rosette, is it not supposed to be used? The docs say that it should work: https://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_racket.html

**Comment by rohinmshah** [comment]
Oh, and in my larger codebase, the issue can be solved by replacing `quasiquote` with calls to `cons` instead, just as in the example above.

**Comment by emina** [comment]
This won't work.  Simple cases of quasiquoting do (e.g., inserting a symbolic value into a concrete list), but nothing that involves symbolic lists will work.  I'll remove this from the docs.

**Comment by rohinmshah** [comment]
The docs now say that `quasiquote` and `unquote` are supported but `unquote-splicing` isn't. However, you can construct bad examples using `unquote` and dotted-tail notation:

```
-> (require rosette)
-> (define-symbolic b boolean?)
-> (define x `(a . ,(if b '(2 3) '(4))))
-> x
'(a . {[b (2 3)] [(! b) (4)]})
-> (length x)
; length: contract violation
;   expected: #<procedure:list?>
;   given: '(a . {[b (2 3)] [(! b) (4)]})
; [,bt for context]
```

**Comment by emina** [comment]
The dotted tail notation is not supported; it's not one of the [lifted forms](https://emina.github.io/rosette/rosette-guide/ch_syntactic-forms_racket.html).
