### ISSUE TITLE
Internal error while decoding sat solution

### ISSUE THREAD

**Issue by AlexKnauth** [emina/rosette#54]
For the program:

```racket
#lang rosette/safe
(define-symbolic offset integer?)
(define-symbolic a (~> integer? integer?))
(define-symbolic disk (~> integer? integer? integer?))

(current-bitwidth #false)
(solve
 (assert
  (forall
   (list offset)
   (= (a offset) (disk 5 offset)))))
```

Rosette throws errors from `decode-body`, one of:
 - `.../rosette/solver/smt/cmd.rkt:113:2: match: no matching clause for 0`
 - `.../rosette/solver/smt/cmd.rkt:113:2: match: no matching clause for '(c3 5 x!1)`

The original undecoded input solution was this hash table:
```racket
'#hash((c3 . (define-fun c3 ((x!1 Int) (x!2 Int)) Int 0))
       (c1 . (define-fun c1 ((x!1 Int)) Int (c3 5 x!1))))
```

The first error case `no matching clause for 0` can be solved by adding these two lines to the match in `decode-body`
```racket
    [(? integer? v0)
     (list (decode-value ran v0))]
```

But the second case with `'(c3 5 x!1)` will be different.

**Comment by AlexKnauth** [comment]
How do rosette `fv`s represent functions that can refer to their arguments? For example how would it represent a symbolic function constrained to be identity?

```
(declare-fun f (Int) Int)
(assert (forall ((x Int)) (= (f x) x)))
(check-sat)
(get-model)
=>
sat
(model
  (define-fun f ((x!0 Int)) Int
    x!0))
```

The current `fv` representation contains a lookup table and a default output. Is there some way for the default output to refer to input variables like `x!0` here? Or would you do this a different way?

**Comment by emina** [comment]
This issue has been resolved.
