### ISSUE TITLE
can the output of union-contents contain symbolic unions?

### ISSUE THREAD

**Issue by stchang** [emina/rosette#55]
Can the output of `union-contents` contain symbolic unions?

The docs say that it cannot but I'm running into some cases where it does (trying to create a small example).

**Comment by emina** [comment]
No, `union-contents` cannot directly contain symbolic unions.  It can, however, contain values that themselves include unions.

**Comment by stchang** [comment]
Ah ok, that describes the cases I'm seeing then, and there's no inconsistency with the docs. Thanks for the clarification.
