### ISSUE TITLE
Z3 outdated?

### ISSUE THREAD

**Issue by sorawee** [emina/rosette#56]
It seems that Z3 for Linux that Rosette uses (https://github.com/emina/rosette/releases/download/v2.0/z3-d89c39cb-x64-ubuntu-14.04.zip) has some bugs and outdated:

```
~/.racket/6.8/pkgs/rosette/bin $ cat test.smt2
(declare-const root1i Real)
(declare-const root2i Real)
(assert (forall ((xi Real)) (= (* (+ xi root1i) (+ xi root2i)) (+ (* xi xi) (* -198.0 xi) -39483.0))))
(check-sat)
(get-model)
(exit)
~/.racket/6.8/pkgs/rosette/bin $ ./z3 --version
~/.racket/6.8/pkgs/rosette/bin $ ./z3 -smt2 test.smt2
unknown
(error "line 5 column 10: model is not available")
```

This works fine on Windows, and on online Z3 (http://rise4fun.com/Z3/) which should give the following output:

```
sat
(model 
  (define-fun root1i () Real
    (- 321.0))
  (define-fun root2i () Real
    123.0)
)
```

**Comment by emina** [comment]
Newer versions of Z3 perform poorly on some of our benchmarks, so we are sticking with this older version for now.  If you need to use the newer version though, you can replace the default binary with your build of the newer one, and everything should work (assuming no major changes in Z3's input/output format).
