### ISSUE TITLE
integer? as a function

### ISSUE THREAD

**Issue by sorawee** [emina/rosette#57]
```
#lang rosette/safe

(define-symbolic x integer?)

(define (f x)
  (cond
    [(= x 543) 1]
    [else "asd"]))

(solve (assert (integer? (f x))))
```

results in `(unsat)`. Perhaps `integer?` is not designed to be used in this way and therefore should be prohibited?

**Comment by stchang** [comment]
Most likely the `current-bitwidth` is too small.

```racket
$ racket
Welcome to Racket v6.7.0.4.
> (require rosette/safe)
> (current-bitwidth 32)
> (define (f x) (cond [(= x 543) 1][else "asf"]))
> (define-symbolic x integer?)
> (evaluate x (solve (assert (integer? (f x)))))
543
```

**Comment by emina** [comment]
To use the theory of integers, `current-bitwidth` has to be set to `#f` (see [here](https://emina.github.io/rosette/rosette-guide/ch_syntactic-forms_rosette.html#%28def._%28%28lib._rosette%2Fquery%2Ffinitize..rkt%29._current-bitwidth%29%29)).
