### ISSUE TITLE
Friendly suggestion/request

### ISSUE THREAD

**Issue by mmontone** [emina/rosette#58]
Hello.

I think your video where you explain Rosette should be added to Rosette homepage somewhere (http://emina.github.io/rosette/): https://youtu.be/KpDyuMIb_E0

Or perhaps it's already there and I'm not seeing it?

It's an extremely good introduction.

Congrats btw. Your work is very impressive and I think you should be awarded for it.

Cheers!

**Comment by emina** [comment]
Thank you for the suggestion and the kind words!

I'll include a link to the talk in the next homepage update.
