### ISSUE TITLE
Unable to use the Z3 wrapper

### ISSUE THREAD

**Issue by Sumith1896** [emina/rosette#63]
I am not able use the `(z3)` wrapper as described [here](https://emina.github.io/rosette/rosette-guide/sec_solvers-and-solutions.html#%28def._%28%28lib._rosette%2Fsolver%2Fsmt%2Fz3..rkt%29._z3%29%29)
```
sumith1896@yoda:~/uwplse/ml$ racket solver-test.rkt 
solver-test.rkt:6:17: z3: unbound identifier in module
  in: z3
  context...:
   /home/sumith1896/uwplse/rosette/rosette/base/form/module.rkt:16:0
   standard-module-name-resolver
```

**Comment by Hardmath123** [comment]
By the way, @rohinmshah pointed out that a temporary workaround is:

```
-> (require (only-in rosette/solver/smt/z3 z3))
-> (z3)
#<z3>
```

**Comment by emina** [comment]
You have to require the right module.  

```
#lang rosette

(require rosette/solver/smt/z3)
(z3)
```
