### ISSUE TITLE
Racket v6.6 version requirement?

### ISSUE THREAD

**Issue by lkuper** [emina/rosette#66]
The Rosette docs say that Racket v6.6 is required, but is this still the case?  Racket is currently at v6.10.1.  Should it be "6.6 or later"?

https://github.com/emina/rosette/blob/4a96e53f0aa1a1dc978b12eb743d0be65ba6d237/rosette/doc/guide/scribble/welcome/welcome.scrbl#L25

**Comment by emina** [comment]
Yes, Rosette will work with Racket 6.6 - 6.10.1.  Fixed the docs.  Thanks!
