### ISSUE TITLE
Request: bitvector size getter

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#70]
Apologies in advance if this is not the best place for requests/questions.

I have a `bitvector` and an `integer` and I need to shift the `bitvector` by the integer amount. How can I convert the integer to a bitvector if I have no accessor for the integer size. With an accessor `bv-size` I could do: `(bvshl my-bv (bv my-int (bv-size my-bv)))`. 

Can we get a `bv-size` if it doesn't exist yet?

**Comment by emina** [comment]
Here are the API calls to perform this conversion, noting that `my-bv` must be a value of bitvector type (or an exception is thrown):

```
#lang rosette

(define (test my-bv my-int)
  (bvshl my-bv (integer->bitvector my-int (type-of my-bv))))

; this works
> (define-symbolic b0 (bitvector 8))
> (test b0 3) 
(bvshl b0 (bv 3 8))

; but this doesn't
> (define-symbolic t boolean?)
> (test (if t b0 (bv 4 4)) 3)
integer->bitvector: expected a bitvector type t
  t: any/c
```
