### ISSUE TITLE
Docs have error

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#71]
On the bitvector documentation at:
https://docs.racket-lang.org/rosette-guide/sec_bitvectors.html

You can see right at the beginning:
```
> (bv 4 (bitvector 7))        ; a bitvector literal of size 7
--
warning: could not find z3 executable in '/home/racket/build-pkgs/user/.racket/6.11/pkgs/rosette/bin/z3.exe/'
(bv 4 7)
```

I assume that warning was not supposed to be there.

**Comment by emina** [comment]
That's not supposed to be there.  It's generated when Rosette docs are built on the Racket server (which doesn't download or run z3). Will look into fixing it.  In the meantime, the GitHub version of the docs is right: 

https://emina.github.io/rosette/rosette-guide/sec_bitvectors.html

**Comment by emina** [comment]
Ok, I pushed a patch that will hopefully cause this message to disappear the next time the docs are rebuilt on the server package.
