### ISSUE TITLE
Redundant assertions in store

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#72]
After running in racket 6.11 with latest rosette:

```racket
#lang rosette

(define opvec (vector 'foo 'bar 'baz 'tar 'taz))

(define-struct insn
  (op
   args-vec))

(define-symbolic* op integer?)
(define-symbolic* arg1 (bitvector 32))
(define-symbolic* arg2 (bitvector 32))

(define-symbolic* res (bitvector 32))

(define i1
  (insn op
        (vector arg1 arg2)))

(define (inter b)
  (case (vector-ref opvec (insn-op b))
    [(foo)
     (printf "rosette: interpreting foo~n")
     (void)]

    [(baz)
     (printf "rosette: interpreting baz~n")
     (set! res (vector-ref (insn-args-vec b)
                           0))]

    [(tar)
     (printf "rosette: interpreting tar~n")
     (set! res (bvadd (vector-ref (insn-args-vec b) 0)
                      (vector-ref (insn-args-vec b) 1)))]

    [else
     (assert #f "unknown op")]))

(printf "store~n")
(pretty-print (asserts))

(inter i1)

(printf "store after inter~n")
(pretty-print (asserts))
```

I get: 
```
Welcome to DrRacket, version 6.11 [3m].
Language: rosette, with debugging; memory limit: 2048 MB.
store
'()
rosette: interpreting foo
rosette: interpreting baz
rosette: interpreting tar
store after inter
(list
 (|| (= 3 op$0) (! (&& (! (= 0 op$0)) (! (= 2 op$0)))))
 (|| (= 3 op$0) (! (&& (! (= 0 op$0)) (! (= 2 op$0)))))
 (< op$0 5)
 (<= 0 op$0))
```

However, `(|| (= 3 op$0) (! (&& (! (= 0 op$0)) (! (= 2 op$0)))))` and `(|| (= 3 op$0) (! (&& (! (= 0 op$0)) (! (= 2 op$0)))))` are equivalent. Why are we adding these to the store? Even if the solver discards one of them later, surely it would be better not to add them to start with.

**Comment by emina** [comment]
We can't reproduce this issue using the master branch (with Racket 6.11 and 6.9). 

Here is the output obtained with master:

```
store
'()
rosette: interpreting foo
rosette: interpreting baz
rosette: interpreting tar
store after inter
(list
 (|| (= 3 op$0) (! (&& (! (= 0 op$0)) (! (= 2 op$0)))))
 (! (&& (&& (! (= 0 op$0)) (! (= 2 op$0))) (! (= 3 op$0))))
 (< op$0 5)
 (<= 0 op$0))
```
Can you try [installing Rosette from source](https://github.com/emina/rosette#installing-from-source) to see if that solves the issue?

**Comment by pmatos** [comment]
I see the same you do but these two are still equivalent. Why are they there at all?
```
 (|| (= 3 op$0) (! (&& (! (= 0 op$0)) (! (= 2 op$0)))))
 (! (&& (&& (! (= 0 op$0)) (! (= 2 op$0))) (! (= 3 op$0))))
```

**Comment by emina** [comment]
Proving the equivalence of two terms involves calling an SMT solver, which Rosette won't do until the final query is constructed, since it's too expensive.  Like other tools, it does a limited number of simplifications upfront (e.g., `x` and `(! x)` is simplified to `#f`)) and leaves the rest to the solver.
