### ISSUE TITLE
Errors are ignored and output is incorrect

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#73]
I might be missing something but I don't think this is appropriate behaviour. Still running with example from #72 but with a slight change:

```racket
#lang rosette

(define opvec (vector 'foo 'bar 'baz 'tar 'taz))

(define-struct insn
  (op
   args-vec))

(define-symbolic* op integer?)
(define-symbolic* arg1 (bitvector 32))
(define-symbolic* arg2 (bitvector 32))

(define-symbolic* res (bitvector 32))

(define i1
  (insn op
        (vector arg1 arg2)))

(define (inter b)
  (case (vector-ref opvec (insn-op b))
    [(foo)
     (printf "rosette: interpreting foo~n")
     (void)]

    [(baz)
     (printf "rosette: interpreting baz~n")
     (set! res (vector-ref (insn-args-vec b)
                           0))]

    [(tar)
     (printf "rosette: interpreting tar~n")
     (set! res (bvadd (vector-ref (insn-args-vec b) 0)
                       (vector-ref (insn-args-vec b) 1)))]

    [else
     (assert #f "unknown op")])
  res)

(printf "store~n")
(pretty-print (asserts))

(define result
  (inter i1))

(printf "store after inter~n")
(pretty-print (asserts))

(printf "result: ~a~n" result)
```

The repl shows:
```
result: (ite (= 0 op$0) res$0 (ite (= 2 op$0) arg1$0 (bvadd arg1$0 arg2$0)))
```

This is correct. We get a value depending on if we went into the `foo`, `baz` or `tar` case.
However, if we introduce an error on purpose:
```racket
#lang rosette

(define opvec (vector 'foo 'bar 'baz 'tar 'taz))

(define-struct insn
  (op
   args-vec))

(define-symbolic* op integer?)
(define-symbolic* arg1 (bitvector 32))
(define-symbolic* arg2 (bitvector 32))

(define-symbolic* res (bitvector 32))

(define i1
  (insn op
        (vector arg1 arg2)))

(define (inter b)
  (case (vector-ref opvec (insn-op b))
    [(foo)
     (printf "rosette: interpreting foo~n")
     (void)]

    [(baz)
     (printf "rosette: interpreting baz~n")
     (set! res (vector-ref (insn-args-vec b)
                           0))]

    [(tar)
     (printf "rosette: interpreting tar~n")
     (set! res (bvadd (vector-ref (insn-args-vec b) 0)
                      (bv ; <- ERROR
                       (vector-ref (insn-args-vec b) 1)
                       (bitvector 32))
           ))]

    [else
     (assert #f "unknown op")])
  res)

(printf "store~n")
(pretty-print (asserts))

(define result
  (inter i1))

(printf "store after inter~n")
(pretty-print (asserts))

(printf "result: ~a~n" result)
```

The error is in the `tar` case where we call `bv` and the `vector-ref` argument already returns a bitvector. In this case this should cause an error except it doesn't.

We get:
```
result: (ite (= 0 op$0) res$0 arg1$0)
```

So it's almost as if since there's an error in the case, this is silently ignored. This makes debugging large rosette programs very, *very* hard.

**Comment by emina** [comment]
This is intended and correct behavior.  To see why, think of an error as a failed assertion.  

For example, consider this code:

```
#lang rosette

(define (foo x)
  (if x
      (+ 3 "foo") ; error
      42))
```

The above code fails only along one path, when 'x' is false.  So, if we try to `verify` the code, Rosette will give us an input on which the execution fails:

```
> (define-symbolic* b boolean?)
> (verify (foo b))
(model
 [b$0 #t])
```

Conversely, if we `solve` for a non-failing execution, we get:

```
> (solve (foo b))
(model
 [b$0 #f])
```

It also helps to examine the assertion store after `(foo b)` is executed:

```
> (foo b)
42
> (asserts)
(list (! b$0))
```
The assertion store faithfully captures the conditions that must be satisfied by non-failing paths through the program.

For another example, see also https://github.com/emina/rosette/issues/36.

**Comment by pmatos** [comment]
OK, understood. Still very annoying though. :)
For some who doesn't care about verification but want to do synthesis instead, ensuring there are no errors in the code is paramount otherwise synthesis will give wrong results because the code silently ignored assertions. Will take a look at Typed Rosette.

**Comment by emina** [comment]
This is the intended behavior for synthesis too, for the same reason as for verification and solving :)

The semantics of the `synthesize` query is the following: the holes must be completed so that there are no failures on any inputs.  So, if the sketch contains an error that is unreachable when holes are carefully picked, we want those errors to be turned into assertions, as in the `verify` and `solve` case.

This comes up in real code in non-trivial ways (when, e.g., applying an interpreter to an AST sketch), but here is a toy example that illustrates the issue:

```
#lang rosette

(define-symbolic b boolean?)

(define (foo x)
  (if b
      (+ x "foo") ; error
      x))

(define-symbolic* x integer?)
(synthesize
 #:forall x
 #:guarantee (foo x))
```
The output is, as expected:

```
(model
 [b #f])
```
