### ISSUE TITLE
$= expects real arguments

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#74]
Not sure yet how I got to this backtrace (it's a very large rosette program), but I end up with:
```
 $=: expected real? arguments
  arguments: (list input$0)
  context...:
   /home/pmatos/.racket/6.11/pkgs/rosette/rosette/base/core/real.rkt:160:10
   /home/pmatos/.racket/6.11/pkgs/rosette/rosette/base/form/control.rkt:30:25
```

I am trying to create a small reproducer in the meantime. Posting this before I find one in case you manage to look at the code and figure out straight away what the problem might be.

**Comment by emina** [comment]
The most likely source of this error is using `=` rather than `equal?'

A quick check to see if this is the issue is to search-replace all occurrences of `=` with `equal?` and see if the error goes away.

**Comment by pmatos** [comment]
That's correct. Thanks.
