### ISSUE TITLE
Synthesize returning sat for unsat model

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#75]
It seems (but it might be my misunderstanding) that synthesize is returning sat for an unsatisfiable model.

```racket
#lang rosette

(define-symbolic input2 input3 (bitvector 32))
(define bv1 (bv 1 (bitvector 32)))

(define formula
  (bveq (bvadd bv1 (bvadd bv1 input3))
        (bvadd input2 (sign-extend (integer->bitvector 16 (bitvector 11))
                                   (bitvector 32)))))

(synthesize
 #:forall '(input2 input3)
 #:guarantee formula)
```

This return an empty model, which means it's `sat`. Why? 
This as far as I am concerned checks if for all possible values of `input2` and `input3`: `input3 + 1+ 1 = input2 + 16` which is obviously not true for all possible values of `input2` and `input3`.

**Comment by emina** [comment]
The [semantics of the `synthesize` query](https://emina.github.io/rosette/rosette-guide/ch_syntactic-forms_rosette.html#%28part._.Synthesis%29) is to fill the holes in such a way that all assertions are satisfied for all inputs. Any completion of the holes is trivially correct for this program because it contains no assertions. Additionally, the `#:forall` subform specifies no symbolic constants: `'(input2 input3)` gives the list `(list 'input2 'input2)` with two literal symbols. Placing `formula` into an assertion and fixing `#:forall` gives the desired behavior:

```
#lang rosette

(define-symbolic input2 input3 (bitvector 32))
(define bv1 (bv 1 (bitvector 32)))

(define formula
  (bveq (bvadd bv1 (bvadd bv1 input3))
        (bvadd input2 (sign-extend (integer->bitvector 16 (bitvector 11))
                                   (bitvector 32)))))

(synthesize
 #:forall (list input2 input3)
 #:guarantee (assert formula))
```
-----
```(unsat)```

**Comment by pmatos** [comment]
Thanks. Is this equivalent to asserting formula and guaranteeing void?

```racket
(assert formula)

(synthesize
 #:forall (list input2 input3)
 #:guarantee (void))
```

**Comment by pmatos** [comment]
I thought the above was correct so I didn't even try it. When I did I found it's not. But why?

This seems to find a model:
```racket
#lang rosette

(define-symbolic input2 input3 (bitvector 32))
(define bv1 (bv 1 (bitvector 32)))

(define formula
  (bveq (bvadd bv1 (bvadd bv1 input3))
        (bvadd input2 (sign-extend (integer->bitvector 16 (bitvector 11))
                                   (bitvector 32)))))

(assert formula)

(synthesize
 #:forall (list input2 input3)
 #:guarantee (void))
```

**Comment by emina** [comment]
The `asserts` issued before a `synthesize` query are [treated as assumptions](https://emina.github.io/rosette/rosette-guide/ch_syntactic-forms_rosette.html#%28part._.Synthesis%29):

> `synthesize` Searches for a binding of symbolic constants to concrete values that has the following properties:
> 1. it does not map constants in the `input-expr` list; and,
> 2. it satisfies all assertions encountered during the evaluation of `guarantee-expr`, for every binding of `input-expr` constants to values that satisfies the **assertions encountered before the invocation of `synthesize`** and during the evaluation of `assume-expr`.
