### ISSUE TITLE
Undocumented : symbolics

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#79]
Is there a reason why the function `symbolics` is undocumented?

https://github.com/emina/rosette/blob/8710f76aa8f20776d2bfe6dda072f7b2c8820847/rosette/base/core/reflect.rkt#L18

If it's not supposed to be part of the public API, does rosette provide another public function that can be used instead?

**Comment by emina** [comment]
There is no reason why the function is undocumented, other than that most use cases don't require it. The function is used internally by the `synthesize` query to collect all symbolic constants that appear in the `#:forall` expression. That is, the client of `synthesize` doesn't need to extract these constants explicitly from a complex value (e.g., a struct with fields that are themselves structs or vectors containing some symbolic constants).  Instead, the client can just pass such a value directly to `#:forall` and `synthesize` will extract the constants internally using `symbolics`.

A lot of tools implement their own versions of `synthesize`, however, and for those tools, it makes sense to use `symbolics` directly.  I'll put it on my to-do list to add it to the public API.

**Comment by emina** [comment]
[Here](https://emina.github.io/rosette/rosette-guide/sec_value-reflection.html#%28def._%28%28lib._rosette%2Fbase%2Fcore%2Freflect..rkt%29._symbolics%29%29) it is.
