### ISSUE TITLE
Error when trying to write to Z3 stdin via pipe on Windows

### ISSUE THREAD

**Issue by dnm** [emina/rosette#8]
I get ``error writing to stream port`` ``system error: The pipe is being closed.; errno=232`` when trying to eval ``(define cex (verify (same poly factored i)))`` with the following set of definitions (and with z3.exe in the bin directory, as per the documentation).

    #lang s-exp rosette
    
    (require rosette/solver/smt/z3)
    (current-solver (new z3%))
    
    ; > (current-solver)
    ; z3%
    
    ; From: http://homes.cs.washington.edu/~emina/rosette/guide/ch_essentials.html
    ; (as of 2016-01-28)
    
    (define (poly x)
     (+ (* x x x x) (* 6 x x x) (* 11 x x) (* 6 x)))
     
    (define (factored x)
     (* x (+ x 1) (+ x 2) (+ x 2)))
     
    (define (same p f x)
     (assert (= (p x) (f x))))
    
    ; "check zeros; all seems well ..."
    ; > (same poly factored 0)
    ; > (same poly factored -1)
    ; > (same poly factored -2)
    
    ; > (define-symbolic i number?)
    ; > (define cex (verify (same poly factored i)))
    ;   -- Currently returns:
    ; error writing to stream port
    ;   system error: The pipe is being closed.; errno=232

Backtrace seems to finger server.rkt as the culprit (but maybe it's really an issue with ``flush-output`` in racket/base? -- see below):

E:\Temp\rosette\rosette\solver\common\server.rkt: 59:4       

    (define/public (write proc)
      (initialize)
      (begin0 (proc in)
              (flush-output in)))

E:\Temp\rosette\rosette\solver\smt\smt.rkt: 30:4       

    (define/public (clear)
      (send server write clear-solver)
      (set!-values (asserts env) (values '() (make-env))))

Perhaps this is related to the issue mentioned here (WRT some Python code using Python's multiprocessing module): http://stackoverflow.com/questions/19070638/python-multiprocessing-ioerror-errno-232-the-pipe-is-being-closed ?

I haven't spent much time on this, and this is as far as I've gotten with diagnosing and troubleshooting this issue so far. Time permitting, I'll continue to dig, but any help would be appreciated. FWIW, I'm on Windows 7 Ultimate SP1 64-bit, and I'm currently using DrRacket 6.1 64-bit.

Thanks!

**Comment by emina** [comment]
The culprit is probably the file name extension.  Can you rename z3.exe to z3?  

(I've only tested the instructions on Linux and Mac.  Windows isn't officially supported but several people did get it to work, and my recollection is that they also had a problem with the file name extensions.)

Hope this helps!

**Comment by dnm** [comment]
Yep, that seemed to be it! Weird! Thanks a ton!

(If I get some time, and I feel up to it, I may submit a PR to fix that on Windows, just to tidy it up for future unsupported users...)

**Comment by emina** [comment]
That would be awesome.  Thanks :)

**Comment by Luo-Liang** [comment]
That saved me.

**Comment by tlringer** [comment]
In case this comes up again and someone else finds themselves here, the same error shows up when z3-path in z3.rkt doesn't actually point to Z3 at all (because of a bad install), so in my case moving Z3 to the expected location worked.
