### ISSUE TITLE
Question: synthesize failure

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#80]
Hello,

I am trying to prove that `forall bitvector x0...xY F`. However, I keep getting unsat. So I did a small experiment whose solution looked pretty obvious:
```racket
(current-bitwidth 32)

(define-symbolic x0 (bitvector 32))

(define sol (synthesize #:forall (list x0)
                        #:assume (assert (bvsgt x0 0))
                        #:guarantee (assert (bvsgt (bvmul x0 (integer->bitvector 2 (bitvector 32))) 
                                                                   x0))))

(if (unsat? sol)
    (printf "unsat core: ~a~n" (core sol))
    (printf "solution: ~a~n" sol))
```

It seems to me that if you assume that x0 is always positive, then `2*x0` should be always larger than `x0`. However, this returns `unsat` which I take it to mean that there is an x0 for which this does not hold.

Then I thought, ok, lets try to find a situation where this is not true and added:
```racket
(solve (assert (=> (bvsgt x0 0) 
                             (! (bvsgt (bvmul x0 (integer->bitvector 2 (bitvector 32))) x0)))))
```

So, assume that `x0 > 0`, for which value `2*x0` is not larger than `x0`? It turns out I get `unsat` as well. I am certainly failing to understand what's the problem. It just occurred to me that it might be related to multiplication overflow, but still  I would get have expected to find a value for `x0` in the `solve` call that would show it to me.

**Comment by emina** [comment]
There are a couple of problems with this example.

First, `bvsgt` takes as input two bit vectors of the same length, so the expression `(bvsgt x0 0)` will always throw an error:

```
#lang rosette

(define-symbolic x0 (bitvector 32))
> (bvsgt x0 0)
. . bvsgt: expected bitvectors of same length
  arguments: (list x0 0)
```

So, this assumption is always false. As a result, there is no way to synthesize a program that takes some inputs satisfying the assumption (since none exist) while also satisfying the guaranteed assertions. 

Second, the intended property doesn't hold for bit vectors because of overflow.  Here is a verification query that demonstrates this:

```
#lang rosette

(define-symbolic x0 (bitvector 32))

(define sol
  (verify  
   #:assume (assert (bvsgt x0 (bv 0 32)))
   #:guarantee (assert (bvsgt (bvmul x0 (bv 2 32)) x0))))

> sol ; counterexample
(model
 [x0 (bv 1935025720 32)])

> (evaluate (bvsgt x0 (bv 0 32)) sol) ; satisfies the assumption
#t

> (evaluate (bvsgt (bvmul x0 (bv 2 32)) x0) sol) ; violates the guarantee
#f
```

**Comment by pmatos** [comment]
Thanks. It makes sense..
It drives me crazy that things like this:
```
(define sol
  (verify  
   #:assume (assert (bvsgt x0 (bv 0 32)))
...
```

are not caught.... I supposed that's what typed rosette is suppose to help with. How is that coming along? Are you involved with that?

**Comment by emina** [comment]
Stephen Chang (@stchang) leads the Typed Rosette project.  I just answer occasional questions :)

**Comment by stchang** [comment]
Hello! Typed Rosette is still a prototype but even so we have used it to port several thousand lines of Rosette code. (I replied to your issue in the other repo if you have further questions.)

**Comment by emina** [comment]
By the way, one useful thing to know about for debugging purposes is the `(asserts)` function, which returns all assertions that have been emitted so far. If this list ever contains `#f`, you can be pretty sure something went wrong.

**Comment by pmatos** [comment]
Thanks for the help on this.
