### ISSUE TITLE
Question: reading printed output

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#81]
Hello,

Sometimes when printing formulas I get a `...`:
```
(ite (bveq input$35 (bvadd (bv 2 32) input$35)) ...))) ...)
```

How can I avoid this and request the whole formula to be printed?

Also, sometimes I get the printed formula as above, other times I see: `{4486849377583105866:41}`

What does this mean?

**Comment by emina** [comment]
The triple dots `...` indicate that the value too big to be printed using [(error-print-width)](https://docs.racket-lang.org/reference/exns.html#%28def._%28%28quote._~23~25kernel%29._error-print-width%29%29) characters. You can increase the printing limit by setting `(error-print-width)` to a higher value.

For example:

```
#lang rosette

> (error-print-width 4)
> (define-symbolic a b c d integer?)
> (+ a b c d)
(+ a ...)
> (error-print-width 400)
> (+ a b c d)
(+ a b c d)
```

In Rosette, [symbolic terms](https://emina.github.io/rosette/rosette-guide/sec_value-reflection.html#%28part._sec~3asymbolic-terms%29) (as in the example above) are printed as s-expressions. [Symbolic unions](https://emina.github.io/rosette/rosette-guide/sec_value-reflection.html#%28part._sec~3asymbolic-unions%29) are displayed as `{id:size}` where `id` is a unique identifier and `size` is the number of elements in the union; unions are printed like symbolic terms.

```
#lang rosette

> (define-symbolic f boolean?)
> (display (if f '(1 2 3) 'a))
{2982055622540433420:2}
> (print (if f '(1 2 3) 'a))
{[f (1 2 3)] [(! f) a]}
```

**Comment by pmatos** [comment]
By symbolic union, you mean that depending on the path taken a symbolic variable might have two different types? hummm, that already sounds like a bug on my side!

**Comment by emina** [comment]
Yes, unions represent the result of merging values of different types, but also values of the same type that have different shape. For example:

```
#lang rosette

> (define-symbolic f boolean?)

> (if f '(1 2 3) 'a) ; different types  
{[f (1 2 3)] [(! f) a]}

> (if f '(1 2 3) '(4 5)) ; same type, different shape (length in this case)
{[f (1 2 3)] [(! f) (4 5)]}

> (if f '(1 2 3) '(4 5 6)) ; same type, same shape
(list (ite f 1 4) (ite f 2 5) (ite f 3 6))
```
