### ISSUE TITLE
Doc: with-asserts-only

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#82]
I just noticed the very useful `with-asserts-only` cousin or `with-asserts`. However, the former is not documented. Maybe it should be added to the docs?

**Comment by emina** [comment]
Sure, [here](https://emina.github.io/rosette/rosette-guide/sec_state-reflection.html#%28form._%28%28lib._rosette%2Fbase%2Fcore%2Fbool..rkt%29._with-asserts-only%29%29) it is.
