### ISSUE TITLE
Feature request: bv print

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#85]
Currently `bv`s show up as `(bv -2069063186 32)`. This is pretty grim to read if you're dealing with large bitvectors. Easier would be hex notation. Can we have a way to request rosette to print them as bitvectors?

Maybe from a param? `(set-printing-bv-as-hex! #t)`

Then this code:
```
  #:methods gen:custom-write
  [(define (write-proc self port mode)
     (fprintf port "(bv ~a ~a)" 
              (bv-value self)
(bitvector-size (bv-type self))))])
```

Could become (untested):
```
  #:methods gen:custom-write
  [(define (write-proc self port mode)
(if (set-printing-bv-as-hex!)
     (fprintf port "(bv 0x~x ~a)" 
              (bv-value self)
(bitvector-size (bv-type self)))
     (fprintf port "(bv ~a ~a)" 
              (bv-value self)
(bitvector-size (bv-type self))))])
```

**Comment by pmatos** [comment]
Actually looking at the code again... We would need to `ufinitize` the value therefore the print function would become:
```racket
(if (set-printing-bv-as-hex!)
    (fprintf port "(bv 0x~x ~a)"
             (ufinitize (bv-value self) (bitvector-size (bv-type self)))
             (bitvector-size (bv-type self)))
    (fprintf port "(bv ~a ~a)" 
              (bv-value self)
             (bitvector-size (bv-type self))))])
```

I would be happy to prepare a pull request if you are open to the idea and could tell me how this gets exported and renamed. I notice you rename everything out with an `@`. So the parameter would become `@set-printing-bv-as-hex!` but how does that then get to the user. Haven't found that piece of the puzzle yet.

**Comment by emina** [comment]
Sure, I've pushed a fix that adopts Z3's convention for printing bitvectors.  If the bitwidth is a multiple of 4, it's displayed in hex; otherwise, it's displayed in binary.

Here is an example:

```
#lang rosette

(bv -1 3)
(bv 1 3)
(bv -3 3)
(bv 3 3)
(bv -1 4)
(bv 1 4)
(bv -3 8)
(bv 3 8)
```

The above prints the following output:

```
(bv #b111 3)
(bv #b001 3)
(bv #b101 3)
(bv #b011 3)
(bv #xf 4)
(bv #x1 4)
(bv #xfd 8)
(bv #x03 8)
```

**Comment by pmatos** [comment]
That's just perfect. Thanks for getting on this so quickly.

**Comment by emina** [comment]
Thanks for the suggestion! :)
