### ISSUE TITLE
Question: cannot solve real number problem

### ISSUE THREAD

**Issue by WanCC1995** [emina/rosette#87]
Hi, I'm trying to solving constraints on reals. The following is my code.

```
(define (close-to? a b) (< (abs (- a b)) 0.1))

(define-symbolic x real?)

(solve (begin
(assert (close-to? x 3))
))
```

However, it just return unsat. Is there any solution for asserting a real number equals to a certain value?

And another question, could Rosette solve strings? like `(define-symbolic x string?)`

**Comment by pmatos** [comment]
Note that the default bitwidth is too small to handle those problems. For real problems I would remove the bitwidth to use the math solvers. 

Try (note I only added the first line to your program, the remainder is left unchanged):
```racket 
#lang rosette

(current-bitwidth #f)

(define (close-to? a b)
  (< (abs (- a b)) 0.1))

(define-symbolic x real?)

(solve (begin (assert (close-to? x 3))))
```

This returns 
```racket
(model
 [x 2 19/20])
```

**Comment by pmatos** [comment]
Let me add... the default bitwidth is 5. You can check it with:
```racket
#lang rosette

(printf "Default bitwidth is ~a~n"
        (current-bitwidth))
```

Which returns:
```racket
Default bitwidth is 5
```

**Comment by emina** [comment]
@pmatos is right:  setting `current-bitwidth`  to `#f` instructs Rosette to treat `integer?` and `real?` as infinite-precision types.  [Here](https://emina.github.io/rosette/rosette-guide/ch_syntactic-forms_rosette.html#%28def._%28%28lib._rosette%2Fquery%2Ffinitize..rkt%29._current-bitwidth%29%29) is a more detailed explanation of the effects of setting `current-bitwidth` to different values.

**Comment by WanCC1995** [comment]
Thanks for your timely reply!
