### ISSUE TITLE
Doesn't find Z3

### ISSUE THREAD

**Issue by Reilithion** [emina/rosette#88]
When I try to use `verify`, I get the error:

```
../../nix/store/8bfa4iwj4g8q77513i0w31wc5aw7br2z-racket-6.10.1/share/racket/collects/racket/private/kw.rkt:1170:47: solution: unrecognized solver output: #<eof>
```

I investigated a bit, and I suspect this is happening because Rosette is not looking in my PATH for the z3 binary, but instead in `../../../bin/z3`. Indeed, when I reproduce this directory structure from the file I have open in DrRacket, I get a different error instead:

```
../../../../../nix/store/8bfa4iwj4g8q77513i0w31wc5aw7br2z-racket-6.10.1/share/racket/collects/racket/private/kw.rkt:1170:47: error writing to stream port
  system error: Broken pipe; errno=32
```

I'm not yet sure what that one's about, but at least it confirms the source of the bad behavior.

**Comment by Reilithion** [comment]
On further investigation, it seems Rosette is providing a version of Z3 in its own bin directory, and this version is compiled against a shared library that does not exist on my system. If I replace the binary with a symbolic link to my system Z3, I get good behavior (`verify` works on an example from the documentation).

**Comment by emina** [comment]
Yes, Rosette expects Z3 to be in a [specific directory](
https://github.com/emina/rosette/blob/567e0ef93d185a98ab54dc10390a1318641d35fc/rosette/solver/smt/z3.rkt#L15).

The second error indicates that Racket was unable to execute the provided binary. 

Rosette was tested on Mac OS, Windows, and recent versions of Ubuntu.
