### ISSUE TITLE
Scalable design to get multiple solutions

### ISSUE THREAD

**Issue by czyssrs** [emina/rosette#89]
For code

```  
#lang rosette
(define-symbolic x integer?)
(solve (begin
(define y (* x 2) )
(assert (> x y) )
)) 
```

It always returns `x=-2`. Currently, I only come out with one solution to get values other than -2:

```
#lang rosette
(define-symbolic x integer?)
(solve (begin
(define y (* x 2) )
(assert (> x y) )
(assert (not (eq? x -2)))
))
```

However, it is not a scalable solution if I want to get multiple values. Is there some racket programming tricks to solve this problem?

**Comment by pmatos** [comment]
Yes, that's how to do it. However, you can wrap up the idea in a loop and get as many examples for `x` as you want.

**Comment by pmatos** [comment]
Here's an example:
```racket
#lang rosette


;; n is the number of examples you need
(define (print-examples n)
  (define-symbolic x integer?)

  (for/fold ([examples '()])
            ([i (in-range n)])
    (define y (* 2 x))
    (define solution
      (solve (assert (> x y))))
    (if (sat? solution)
        (let ([x-value (evaluate x solution)])
          (assert (not (= x x-value)))
          (cons x-value examples))
        examples)))
```

```racket
> (print-examples 5)
'(-8 -1 -5 -6 -2)
```

Note this could be improved in case of an unsatisfiable solution is found mid-search. Currently it finishes the looping for all remaining values instead of breaking.

**Comment by WanCC1995** [comment]
Looks great! But how to manage this loop if there are unknown number of symbolics?

**Comment by pmatos** [comment]
@WanCC1995 I am not sure I understand what is the issue with the several number of symbolics. Do you have an example of what you need to do?

Also, it only retrieves as many answers as you need. If you need only 2 answers it'll give you 2 answers. If you need 1000, it will give you 1000. The issue, as I initially said, and couldn't be bothered to fix is that if you ask for 1000 answers but only 500 exist, it will still loop 1000 times. 

We only add one new assert per loop, we don't reassert everything over again. The asserts are kept in the assert store that just keeps growing.

**Comment by WanCC1995** [comment]
Maybe like this?

```
#lang rosette
(define-symbolic x integer?)
(define-symbolic y integer?)
(solve (begin
(assert (> x y) )
)) 
```

**Comment by emina** [comment]
Here is another solution that uses an as-of-yet-undocumented feature of Rosette for better efficiency.  This solution relies on Z3's incremental solving, and it will take care of models with multiple symbolic values:

```
#lang rosette

(define (¬solution sol)
  (apply || (for/list ([(c v) (model sol)]) (! (equal? c v)))))

(define (solve* constraint [N +inf.0])
  (define solve-many (solve+))
  (reverse
   (let loop ([sol (solve-many constraint)][i 0])
     (if (and (sat? sol) (< i N))
         (cons sol (loop (solve-many (¬solution sol)) (add1 i)))
         (list)))))
    
(current-bitwidth #f)

(define-symbolic x integer?)
(define-symbolic y integer?)

(pretty-print (solve* (> x y) 5)) ; at most 5 solutions

```

This will print

```
'((model
 [x -3]
 [y -4]) (model
 [x -2]
 [y -3]) (model
 [x -1]
 [y -2]) (model
 [x 0]
 [y -1]) (model
 [x 1]
 [y 0]))
```

If you need to first collect some assertions and then get their solutions, you can combine the above code with the [`with-asserts-only`](https://emina.github.io/rosette/rosette-guide/sec_state-reflection.html#%28form._%28%28lib._rosette%2Fbase%2Fcore%2Fbool..rkt%29._with-asserts-only%29%29) form:

```
#lang rosette

(define (¬solution sol)
  (apply || (for/list ([(c v) (model sol)]) (! (equal? c v)))))

(define (solve* constraint [N +inf.0])
  (define solve-many (solve+))
  (reverse
   (let loop ([sol (solve-many constraint)][i 0])
     (if (and (sat? sol) (< i N))
         (cons sol (loop (solve-many (¬solution sol)) (add1 i)))
         (list)))))
    
(current-bitwidth #f)

(define-symbolic x integer?)
(define-symbolic y integer?)

(define (some-procedure)
  (assert (> x y))
  (assert (> x 0)))

(pretty-print ; at most 5 solutions
 (solve*
  (apply && (with-asserts-only (some-procedure)))
  5)) 
```

The above will print:

```
'((model
 [x 2]
 [y -3]) (model
 [x 1]
 [y -3]) (model
 [x 1]
 [y -2]) (model
 [x 1]
 [y -1]) (model
 [x 1]
 [y 0]))
```

I'll add `solve+` to the docs.

**Comment by czyssrs** [comment]
Thank you, it works for me! @emina

**Comment by emina** [comment]
Great!

I've added [documentation for `solve+`](https://emina.github.io/rosette/rosette-guide/ch_syntactic-forms_rosette.html#%28def._%28%28lib._rosette%2Fquery%2Fform..rkt%29._solve%2B%29%29).

Note that the above approach to obtaining multiple solutions will not work if any of the symbolic constants are [uninterpreted functions](https://emina.github.io/rosette/rosette-guide/sec_UF.html).   There is a way to handle that case as well, but it's more complicated.
