### ISSUE TITLE
Question: Thread-safe rosette

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#90]
I implemented a threaded solver based on rosette and thought all was fine until I started getting the very strange error:
```
.racket/6.12/pkgs/rosette/rosette/solver/smt/z3.rkt:104:printf: output port is closed
```
After digging in rosette code and some attempts to reproduce this I found the issue:
```
#lang rosette

(current-bitwidth #f)

;; Issues 100 threads
(define thds
  (for/list ([i (in-range 100)])
    (thread
     (thunk
      (define-symbolic* v z integer?)
      (sleep (random))
      (verify
       (assert (and (> v 0)
                    (not (= z 0))
                    (= (* z v) 0))))))))

(for ([thd (in-list thds)])
  (thread-wait thd))

(printf "Done")
```

This generates a bunch of horrible errors. It turns out rosette is not thread safe. I understand the decision, however I wonder what's the best way to get rosette to behave under several threads.

I can imagine two ways:
1. Implement thread safety into rosette by ensuring that each thread can have a solver instance. Not completely sure how to approach this yet but it's certainly feasible.
2. Implement thread safety at the application level by assuming rosette is not thread safety and creating a lock on rosette usage.

Do you have any thoughts on this?

**Comment by pmatos** [comment]
Ah! :) I am happy! 

With #91 fixed through #92, the solution to the above problem is to instantiate a new solver per thread.
```racket
#lang rosette

(current-bitwidth #f)

;; Issues 100 threads
(define thds
  (for/list ([i (in-range 100)])
    (parameterize ([current-solver (z3)])
      (thread
       (thunk
        (define-symbolic* v z integer?)
        (sleep (random))
        (verify
         (assert (and (> v 0)
                      (not (= z 0))
                      (= (* z v) 0)))))))))

(for ([thd (in-list thds)])
  (thread-wait thd))

(printf "Done")
```

The above works like a charm, but yes you get 100 z3 processes instantiated.

**Comment by pmatos** [comment]
Fell free to close this if you have nothing to add.

**Comment by emina** [comment]
Yes, you'll want N independent instances of z3 in order to achieve concurrency.  

Note also that [Racket threads don't run in parallel](https://docs.racket-lang.org/reference/eval-model.html#%28part._thread-model%29); rather, their execution is interleaved on a single processor. If you need true concurrency during symbolic evaluation (not just solving), you might want to check out [Racket places](https://docs.racket-lang.org/reference/places.html).

Finally, you might also want to consider giving each thread its own `term-cache` in order to [avoid deadlocks](https://docs.racket-lang.org/reference/hashtables.html).

```
#lang rosette

(require rosette/solver/smt/z3)

(current-bitwidth #f)

;; Issues 100 threads
(define thds
  (for/list ([i (in-range 100)])
    (parameterize ([current-solver (z3)]
                   [term-cache (hash-copy (term-cache))])
      (thread
       (thunk
        (define-symbolic* v z integer?)
        (sleep (random))
        (verify
         (assert (and (> v 0)
                      (not (= z 0))
                      (= (* z v) 0)))))))))

(for ([thd (in-list thds)])
  (thread-wait thd))

(printf "Done")
```

**Comment by pmatos** [comment]
Thanks for the hint on the usage of `term-cache`. In my distributed architecture I am using remote places for distributation and threads for single core usage so threads are what I really need in this case. :)
