### ISSUE TITLE
z3 is undefined

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#91]
As opposed to what's said here:
https://docs.racket-lang.org/rosette-guide/sec_solvers-and-solutions.html?q=rosette#%28def._%28%28lib._rosette%2Fsolver%2Fsmt%2Fz3..rkt%29._z3%29%29

Rosette does not recognize `z3`:
```
#lang rosette
(define solver-z3 (z3))
```

Output:
```
z3: unbound identifier in module in: z3
```

**Comment by emina** [comment]
Right, `z3` needs to imported separately.

The blue box above the docs for `z3` shows the library that contains the solver (following Racket convention):
`(require rosette/solver/smt/z3)`

**Comment by pmatos** [comment]
Thanks. Makes total sense.
