### ISSUE TITLE
Question: smt2 output

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#95]
Is there a way to output the SMT problem sent to Z3 in smt format?

I can create a fake z3 that gathers the communication between rosette and z3 but if there was a simpler way it would be great.

**Comment by emina** [comment]
The simplest hack (which I use when needing the SMT output) is to comment out [this line](https://github.com/emina/rosette/blob/8fa04ccfc939af9869abd1e98c3bbedac7fef207/rosette/solver/smt/smtlib2.rkt#L42), and then recompile Rosette.

If you need a more flexible / systematic way to do this, let me know, and I'll add a mechanism for it.

**Comment by pmatos** [comment]
Thanks @emina 

That hack should be enough for now. If I end up doing something more robust I will send a pull request.
