### ISSUE TITLE
solver and current-solver confusion

### ISSUE THREAD

**Issue by willghatch** [emina/rosette#96]
I am confused about the interaction between `assert`, `asserts`, `with-asserts`, etc, and `solver-assert`, `solver-push`, `current-solver`, etc.

Here is a quick example:

```
#lang rosette

(define-symbolic a b integer?)

;; I expect that this desugars essentially to:
;; (solver-assert (current-solver) (= a 5))
(assert (= a 5))
(solver-assert (current-solver) (list (= a b)))
;; I expect (unsat), but the two assertions don't seem to be used together.
(verify (assert (= b 5))) ; -> (model [a 5] [b -6])
(solver-push (current-solver))
(solver-assert (current-solver) (list (not (= 5 b))))
;; I expect this check to be unsat because of the three asserts,
;; but the first assert doesn't seem to be in the current-solver.
(solver-check (current-solver)) ; -> (model [b 0])
;; (asserts) gives me only the original assert, not the asserts on current-solver
(asserts) ; -> (list (= a 5))
;; And I don't seem to have any other API to get the asserts on the current-solver

```

The docs say “The current-solver parameter holds the solver object used for answering solver-aided queries.”, so I would really expect `assert` forms to desugar to `solver-assert` forms with the `current-solver`, or otherwise be equivalent to doing that, as well as other functions that interact with the solver like `verify` to use the `current-solver`.  Why are they separate?  Maybe the documentation about `current-solver` should be updated.

If they are meant to be separate interfaces that don't interact, I also wonder why the interfaces are not more symmetrical -- eg. I see no `solver-asserts` analogous to `asserts`, nor `solver-with-asserts`, etc.  On the other hand there is no push/pop for assertions when using `assert` instead of `solver-assert` (though it could be implemented via `asserts` and `clear-asserts!`, but maybe with worse performance?).

Maybe I'm just deeply misunderstanding something.  My root issue is that I want to be able to use push/pop functionality along with `asserts`.  Why are things this way, or what am I missing?

Thanks!

(Also, I'm using Racket 6.12 and ran `raco pkg install rosette` on April 2.  Thanks for making Rosette, I think it's pretty cool despite my confusion.)

**Comment by emina** [comment]
The `assert` form doesn't call or directly interacts with `solver-assert` in any way.  Rather, `(assert expr)` pushes the value of `expr` onto Rosette's assertion stack, which is accessible via `asserts`. This stack is separate and distinct from the solver's assertion stack, which is maintained internally by the solver and inaccessible to Rosette.

The low-level solver interface (which includes `solver-assert`, `push` and `pop`) is called by queries (such as `verify` or `synthesize`), which transfer the contents of the assertion stack to the solver according to the query's semantics.

From your example code, I'm guessing what you need is incremental solving.  The easiest way to access that functionality is via [`solve+'](https://emina.github.io/rosette/rosette-guide/ch_syntactic-forms_rosette.html#%28def._%28%28lib._rosette%2Fquery%2Fform..rkt%29._solve%2B%29%29), as described [here](https://github.com/emina/rosette/issues/89).
