### ISSUE TITLE
Tests failing on HEAD

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#97]
Someone should try to understand why tests are failing on HEAD:
https://travis-ci.org/emina/rosette/builds/346912814

This is the link for the first time the pipeline failed on HEAD. The latest failure has a different failure reason.
I wonder if it's really a good idea to allow failures.

**Comment by pmatos** [comment]
The tests fail on HEAD (latest fail) because racket started providing `??` as an identifier:
https://github.com/racket/racket/commit/8d607b83f9966a4e3d3ae269dbc9960f3810d7ae

**Comment by emina** [comment]
Thanks for diagnosing the issue.

Unfortunately, there is tricky to fix without breaking other things (see [Racket issue 2031](https://github.com/racket/racket/issues/2031)), so we'll let the HEAD build fail for the time being.

**Comment by pmatos** [comment]
With https://github.com/racket/racket/pull/2033 merged, I think rosette should be fine now.
