### ISSUE TITLE
Search in the documentation produces 404

### ISSUE THREAD

**Issue by gergia** [emina/rosette#98]
Hi,

I was experimenting with Rosette and noticed a problem: when I try to search through the documentation, the 404 is returned.
For example, if I search for `solve`, a request to https://emina.github.io/rosette/search/index.html?q=solve is created, but that returns 404.

**Comment by emina** [comment]
Hi!  Yes, this is a known issue (#52).  The search function works only when invoked through the distribution docs:

https://docs.racket-lang.org/search/index.html?q=solve
